"""``pegasus-workflows mcp`` — stdio MCP server for AI coding agents.

A thin shell over existing SDK internals (manifest validation, project
scaffolding, packaging, and the integration-config dry-run gate).  It does
NOT re-implement any business logic — every tool delegates straight to the
corresponding CLI helper.

The ``mcp`` extra must be installed::

    pip install 'pegasus-workflows-sdk[mcp]'

Resources
---------
``pegasus://guide/authoring``
    Authoring guide: import surface, determinism rule, input contract.
``pegasus://guide/input-contract``
    The three input shapes + a worked resolver example.
``pegasus://reference/manifest``
    Manifest fields and constraints, generated from ``manifest.py`` constants.
``pegasus://reference/api``
    ``PegasusClient`` method surface, generated by introspection.

Tools
-----
``scaffold_workflow(name, dest)``
    Scaffold a new workflow project (wraps ``pegasus-workflows init``).
``validate_manifest(path_or_toml)``
    Validate a manifest file path or raw TOML text.
``package_project(project_dir)``
    Package declared workflows into ``dist/`` (wraps ``pegasus-workflows package``).
``validate_integration_config(integration_id, mapping, rules, corpus, base_url, token)``
    Dry-run the publish gate — no write (wraps ``PegasusClient.validate_integration_config``).
"""

from __future__ import annotations

import dataclasses
import inspect
import tempfile
from pathlib import Path
from typing import Any

import typer

from ..api import PegasusClient
from ..manifest import (
    MANIFEST_FILENAME,
    MANIFEST_TIMEOUT_MAX_SECONDS,
    NAME_REGEX,
    VERSION_REGEX,
    Manifest,
    ManifestError,
    load_manifest,
)
from .init import render_project
from .package import package_project as _pkg_project

__all__ = [
    "mcp_command",
    "resource_guide_authoring",
    "resource_guide_input_contract",
    "resource_reference_manifest",
    "resource_reference_api",
    "tool_scaffold_workflow",
    "tool_validate_manifest",
    "tool_package_project",
    "tool_validate_integration_config",
]

#: Shown when the user runs ``pegasus-workflows mcp`` without the extra installed.
_MISSING_EXTRA_MSG = (
    "The 'mcp' extra is required: pip install 'pegasus-workflows-sdk[mcp]'"
)


# ── Resources (plain functions — no MCP runtime dependency) ──────────────────


def resource_guide_authoring() -> str:
    """Authoring guide: import surface, determinism rule, and input contract pointer."""
    return """\
# Pegasus Workflow Authoring Guide

## Import surface

Import Temporal primitives and the decorator from ``pegasus_workflows``:

    from pegasus_workflows import activity, pegasus_workflow, workflow
    from pegasus_workflows.api import PegasusClient   # activities only — never in workflow code

Decorate your workflow class:

    @pegasus_workflow(name="demo", version="0.1.0")
    class HelloWorkflow:
        @workflow.run
        async def run(self, arg: dict | str) -> str:
            ...

The ``name`` in ``@pegasus_workflow`` **must match** the manifest ``name`` field
exactly — do not use the Python class name.

## Determinism rule

Workflow code runs inside the Temporal determinism sandbox. It MUST NOT:
- perform any I/O (file, network, subprocess, environment reads)
- import ``httpx``, ``requests``, or any I/O library
- use ``random``, ``datetime.now()``, or any non-deterministic call

All I/O belongs in ``@activity.defn`` functions, which run outside the sandbox.
Use ``PegasusClient`` only inside activities, never inside workflow methods.

## Activities

    from pegasus_workflows import activity
    from pegasus_workflows.api import PegasusClient

    @activity.defn
    async def fetch_quote(quote_id: str) -> dict:
        client = PegasusClient(base_url="https://...", token="vnd_...")
        return client.get_workflow(quote_id)  # example — use the right method

## Input contract

See ``pegasus://guide/input-contract`` for the three argument shapes your
``run()`` method must handle (trigger-fired, manual run, CLI test).
"""


def resource_guide_input_contract() -> str:
    """The three input shapes + a worked resolver example."""
    return """\
# Pegasus Workflow Input Contract

Your ``run()`` method receives a single positional argument. Its shape depends
on how the workflow was started:

## Shape 1 — Trigger-fired (domain-event trigger)

The dispatcher injects the full event envelope:

    {
        "domainEventId": "<uuid>",
        "eventType": "quote.accepted",
        "occurredAt": "<ISO-8601>",
        "payload": {"quoteId": "<id>", "moveId": "<id>"}
    }

Read ids from ``arg["payload"]["quoteId"]`` etc. The payload is a pointer,
not a snapshot — always re-fetch authoritative state from the Pegasus API.

## Shape 2 — Manual run

``POST /api/v1/workflows/:id/run`` passes:

    {"executionId": "<uuid>", "input": <user-supplied dict>}

Read your business data from ``arg["input"]``.

## Shape 3 — CLI test

``pegasus-workflows test <name>`` passes a raw string for local-dev parity.

## Recommended pattern: a module-level resolver (unit-testable)

Write a plain function — not a method — so it stays testable without a Temporal
worker context:

    def _resolve_quote_id(arg: dict | str) -> str:
        if isinstance(arg, str):
            return arg
        payload = arg.get("payload") if isinstance(arg, dict) else None
        if isinstance(payload, dict) and payload.get("quoteId"):
            return str(payload["quoteId"])
        inp = arg.get("input") if isinstance(arg, dict) else None
        if isinstance(inp, dict) and inp.get("quote_id"):
            return str(inp["quote_id"])
        return "quote-unknown"
"""


def resource_reference_manifest() -> str:
    """Manifest reference generated from ``manifest.py`` constants at serve time."""
    field_lines = [f"- ``{f.name}``" for f in dataclasses.fields(Manifest)]
    return (
        "# Pegasus Manifest Reference\n\n"
        "Generated from ``pegasus_workflows.manifest`` — constants are read at\n"
        "serve time so this document stays in sync automatically.\n\n"
        "## File name\n\n"
        f"``{MANIFEST_FILENAME}``\n\n"
        "## Name constraint\n\n"
        f"Regex: ``{NAME_REGEX.pattern}``\n\n"
        "Lowercase letters, digits, ``_``, ``-``, 1–64 characters.\n\n"
        "## Version constraint\n\n"
        f"Regex: ``{VERSION_REGEX.pattern}``\n\n"
        "Semver subset: ``MAJOR.MINOR.PATCH`` with optional pre-release suffix\n"
        "(``-beta.1``, ``-rc.2``, ...).\n\n"
        "## Timeout constraint\n\n"
        f"``timeout_seconds`` max: ``{MANIFEST_TIMEOUT_MAX_SECONDS}`` s.\n"
        "The manifest may LOWER the platform default, never raise it.\n\n"
        "## Manifest fields (``Manifest`` dataclass)\n\n"
        + "\n".join(field_lines)
        + "\n\n"
        "## Example ``pegasus-workflows.toml``\n\n"
        "    [[workflow]]\n"
        '    name = "send_quote_followup"\n'
        '    version = "0.1.0"\n'
        '    entry_points = ["send_quote_followup.workflow:SendQuoteFollowup"]\n'
        '    source_dir = "send_quote_followup"   # optional, defaults to name\n'
        '    description = "Follow up on accepted quotes."\n'
        '    required_actions = ["ReadQuote", "EmitTenantEvent"]\n'
        "    timeout_seconds = 300\n"
    )


def resource_reference_api() -> str:
    """PegasusClient method surface, generated by introspection at serve time."""
    lines = [
        "# Pegasus API Reference (PegasusClient)",
        "",
        "Generated by introspecting ``pegasus_workflows.api.PegasusClient`` at serve",
        "time — adding or renaming a method or changing its docstring updates this",
        "resource automatically.",
        "",
    ]
    for name, method in inspect.getmembers(PegasusClient, predicate=inspect.isfunction):
        if name.startswith("_"):
            continue
        try:
            sig = inspect.signature(method)
            sig_str = f"{name}{sig}"
        except (ValueError, TypeError):
            sig_str = name
        doc = inspect.getdoc(method) or ""
        lines.append(f"## {sig_str}")
        if doc:
            lines.append("")
            lines.append(doc)
        lines.append("")
    return "\n".join(lines)


# ── Tools (plain functions — no MCP runtime dependency) ──────────────────────


def tool_scaffold_workflow(name: str, dest: str) -> dict[str, Any]:
    """Scaffold a new workflow project at ``dest/name``.

    Wraps :func:`pegasus_workflows.cli.init.render_project`.

    Returns:
        ``{"ok": True, "project_dir": str, "files": [relative_path, ...]}``
        on success, or ``{"ok": False, "error": str}`` on failure.
    """
    dest_path = Path(dest).resolve()
    try:
        project_dir = render_project(name, dest_path)
    except (ValueError, FileExistsError, OSError) as exc:
        return {"ok": False, "error": str(exc)}

    files = sorted(
        str(p.relative_to(project_dir))
        for p in project_dir.rglob("*")
        if p.is_file()
    )
    return {"ok": True, "project_dir": str(project_dir), "files": files}


def tool_validate_manifest(path_or_toml: str) -> dict[str, Any]:
    """Validate a manifest file path or raw TOML text.

    Wraps :func:`pegasus_workflows.manifest.load_manifest`.  If *path_or_toml*
    resolves to an existing file, it is parsed directly.  Otherwise the value
    is treated as TOML text and written to a temporary file for parsing.

    Returns:
        ``{"ok": True, "manifests": [...]}`` on success, or
        ``{"ok": False, "error": str}`` on validation failure.
    """
    p = Path(path_or_toml)
    if p.is_file():
        try:
            manifests = load_manifest(p)
        except ManifestError as exc:
            return {"ok": False, "error": str(exc)}
        return {"ok": True, "manifests": [_manifest_to_dict(m) for m in manifests]}

    # Treat as raw TOML text.
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".toml", encoding="utf-8", delete=False
        ) as tmp:
            tmp_path = Path(tmp.name)  # assign before write so finally can always unlink
            tmp.write(path_or_toml)
        try:
            manifests = load_manifest(tmp_path)
        except ManifestError as exc:
            return {"ok": False, "error": str(exc)}
    except OSError as exc:
        # NamedTemporaryFile creation or write failed — return structured error.
        return {"ok": False, "error": f"could not create temporary file: {exc}"}
    finally:
        if tmp_path is not None:
            tmp_path.unlink(missing_ok=True)

    return {"ok": True, "manifests": [_manifest_to_dict(m) for m in manifests]}


def _manifest_to_dict(m: Manifest) -> dict[str, Any]:
    return {
        "name": m.name,
        "version": m.version,
        "entry_points": list(m.entry_points),
        "source_dir": m.source_dir,
        "description": m.description,
        "required_actions": list(m.required_actions),
        "timeout_seconds": m.timeout_seconds,
    }


def tool_package_project(project_dir: str) -> dict[str, Any]:
    """Package every workflow declared in ``project_dir`` into ``dist/``.

    Wraps :func:`pegasus_workflows.cli.package.package_project`.

    Returns:
        ``{"ok": True, "artifacts": [{name, version, zip_path, size_bytes}, ...]}``
        on success, or ``{"ok": False, "error": str}`` on failure.
    """
    try:
        results = _pkg_project(Path(project_dir).resolve())
    except (ManifestError, OSError) as exc:
        return {"ok": False, "error": str(exc)}

    artifacts = [
        {
            "name": manifest.name,
            "version": manifest.version,
            "zip_path": str(zip_path),
            "size_bytes": zip_path.stat().st_size,
        }
        for manifest, zip_path in results
    ]
    return {"ok": True, "artifacts": artifacts}


def tool_validate_integration_config(
    integration_id: str,
    mapping: Any,
    rules: Any,
    corpus: Any,
    base_url: str,
    token: str,
) -> dict[str, Any]:
    """Dry-run the integration config publish gate. No write.

    Constructs a :class:`~pegasus_workflows.api.PegasusClient` from *base_url*
    and *token*, then calls
    :meth:`~pegasus_workflows.api.PegasusClient.validate_integration_config`.

    Returns:
        ``{"ok": True, "report": {...}}`` on success, or
        ``{"ok": False, "error": str}`` on failure.
    """
    client = PegasusClient(base_url=base_url, token=token)
    try:
        report = client.validate_integration_config(
            integration_id, mapping=mapping, rules=rules, corpus=corpus
        )
        return {"ok": True, "report": report}
    except Exception as exc:  # broad catch: httpx, PegasusApiError, network errors
        return {"ok": False, "error": str(exc)}


# ── MCP server builder ────────────────────────────────────────────────────────


def _build_server(FastMCP: type) -> Any:  # type: ignore[type-arg]
    """Wire resources and tools onto a fresh FastMCP instance.

    Receives the FastMCP class as an argument so the caller controls when
    the ``mcp`` library is imported and tests can wire it without starting
    a real stdio loop.
    """
    server = FastMCP(
        "pegasus-workflows",
        instructions=(
            "Use the resources to understand Pegasus workflow authoring rules "
            "and the tools to scaffold, validate, package, and dry-run-gate "
            "workflows without triggering any network writes."
        ),
    )

    @server.resource("pegasus://guide/authoring")
    def _res_guide_authoring() -> str:
        return resource_guide_authoring()

    @server.resource("pegasus://guide/input-contract")
    def _res_guide_input_contract() -> str:
        return resource_guide_input_contract()

    @server.resource("pegasus://reference/manifest")
    def _res_reference_manifest() -> str:
        return resource_reference_manifest()

    @server.resource("pegasus://reference/api")
    def _res_reference_api() -> str:
        return resource_reference_api()

    @server.tool()
    def scaffold_workflow(name: str, dest: str) -> dict:  # type: ignore[type-arg]
        """Scaffold a new workflow project at dest/name (wraps pegasus-workflows init)."""
        return tool_scaffold_workflow(name, dest)

    @server.tool()
    def validate_manifest(path_or_toml: str) -> dict:  # type: ignore[type-arg]
        """Validate a manifest file path or raw TOML text."""
        return tool_validate_manifest(path_or_toml)

    @server.tool()
    def package_project(project_dir: str) -> dict:  # type: ignore[type-arg]
        """Package every workflow in project_dir into dist/ (wraps pegasus-workflows package)."""
        return tool_package_project(project_dir)

    @server.tool()
    def validate_integration_config(
        integration_id: str,
        mapping: Any,
        rules: Any,
        corpus: Any,
        base_url: str,
        token: str,
    ) -> dict:  # type: ignore[type-arg]
        """Dry-run the integration config publish gate. No write."""
        return tool_validate_integration_config(
            integration_id, mapping, rules, corpus, base_url, token
        )

    return server


# ── Typer command ─────────────────────────────────────────────────────────────


def mcp_command() -> None:
    """Start a stdio MCP server for AI coding agents (requires the ``mcp`` extra).

    Exposes SDK resources and safe tools so any MCP-compatible agent can
    scaffold, validate, and package Pegasus workflows without network side
    effects.  Network-mutating operations (push, publish, run) are not exposed
    and remain human-gated via the CLI.

    Install the extra first::

        pip install 'pegasus-workflows-sdk[mcp]'
    """
    try:
        from mcp.server.fastmcp import FastMCP
    except ImportError:
        typer.secho(_MISSING_EXTRA_MSG, fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from None

    server = _build_server(FastMCP)
    server.run("stdio")
