"""``pegasus-workflows mcp`` — stdio MCP server for AI coding agents.

A thin shell over existing SDK internals (manifest validation, project
scaffolding, packaging, and the integration-config dry-run gate).  It does
NOT re-implement any business logic — every tool delegates straight to the
corresponding CLI helper.

The MCP server ships in the base package — a plain install has everything::

    pip install pegasus-workflows-sdk

Resources
---------
``pegasus://guide/authoring``
    Authoring guide: import surface, determinism rule, input contract.
``pegasus://guide/input-contract``
    The three input shapes + a worked resolver example.
``pegasus://guide/secrets-config``
    How to publish and use per-tenant workflow secrets & configuration.
``pegasus://reference/manifest``
    Manifest fields and constraints, generated from ``manifest.py`` constants.
``pegasus://reference/api``
    ``PegasusClient`` method surface, generated by introspection.
``pegasus://reference/integration-config``
    How to author + publish an integration config (files, floors, rules, the
    ingress ``inbound`` block, the publish gate) — no platform source needed.
``pegasus://reference/floors``
    Live list of built-in floors (canonicalFields + factCatalog + inputFieldRoots)
    to author against.
``pegasus://reference/openapi``
    The API's OpenAPI 3.1 spec (live), so an agent can inspect every endpoint.

Tools
-----
``scaffold_workflow(name, dest)``
    Scaffold a new workflow project (wraps ``pegasus-workflows init``).
``validate_manifest(path_or_toml)``
    Validate a manifest file path or raw TOML text.
``diagram_prompt(project_dir, workflow=None)``
    Build the bring-your-own-agent prompt(s) for drawing each ``workflow.mmd`` —
    the calling agent produces the Mermaid diagram itself (read-only, no network).
``package_project(project_dir)``
    Package declared workflows into ``dist/`` (wraps ``pegasus-workflows package``).
``validate_integration_config(integration_id, mapping, rules, corpus, base_url, token)``
    Dry-run the publish gate — no write (wraps ``PegasusClient.validate_integration_config``).
``list_deployments(project_dir)``
    Read the project's ``deployments.toml`` ledger (read-only, no network).
``list_profiles()``
    List credential profile names + api_root — never a key (read-only, no network).
"""

from __future__ import annotations

import dataclasses
import inspect
import tempfile
from pathlib import Path
from typing import Any

import typer

from ..api import PegasusClient
from ..credentials import ProfileError, list_profile_summaries
from ..deployments import read_deployments
from ..manifest import (
    DIAGRAM_FILENAME,
    MANIFEST_FILENAME,
    MANIFEST_TIMEOUT_MAX_SECONDS,
    NAME_REGEX,
    VERSION_REGEX,
    Manifest,
    ManifestError,
    load_manifest,
)
from .diagram import build_diagram_prompt, gather_source
from .init import render_project
from .package import package_project as _pkg_project

__all__ = [
    "mcp_command",
    "resource_guide_authoring",
    "resource_guide_input_contract",
    "resource_guide_secrets_config",
    "resource_reference_manifest",
    "resource_reference_api",
    "tool_scaffold_workflow",
    "tool_validate_manifest",
    "tool_diagram_prompt",
    "tool_package_project",
    "tool_validate_integration_config",
    "tool_list_deployments",
    "tool_list_profiles",
]

#: Shown if the ``mcp`` dependency is somehow absent. It ships in the BASE package
#: (as of 0.8.1), so the remedy is a reinstall — not an extra. Defensive only.
_MISSING_EXTRA_MSG = (
    "The MCP server dependency 'mcp' is missing from this environment — it ships "
    "in the base pegasus-workflows-sdk package. Reinstall to restore it: "
    "pip install --upgrade pegasus-workflows-sdk"
)


# ── Resources (plain functions — no MCP runtime dependency) ──────────────────


def resource_guide_authoring() -> str:
    """Authoring guide: import surface, determinism rule, and input contract pointer."""
    return """\
# Pegasus Workflow Authoring Guide

## Import surface

Import Temporal primitives and the decorator from ``pegasus_workflows``:

    from pegasus_workflows import activity, pegasus_workflow, workflow
    from pegasus_workflows.api import PegasusClient   # activities only — never in workflow code

Decorate your workflow class:

    @pegasus_workflow(name="demo", version="0.1.0")
    class HelloWorkflow:
        @workflow.run
        async def run(self, arg: dict | str) -> str:
            ...

The ``name`` in ``@pegasus_workflow`` **must match** the manifest ``name`` field
exactly — do not use the Python class name.

## Determinism rule

Workflow code runs inside the Temporal determinism sandbox. It MUST NOT:
- perform any I/O (file, network, subprocess, environment reads)
- import ``httpx``, ``requests``, or any I/O library
- use ``random``, ``datetime.now()``, or any non-deterministic call

All I/O belongs in ``@activity.defn`` functions, which run outside the sandbox.
Use ``PegasusClient`` only inside activities, never inside workflow methods.

## Activities

Build the client with ``PegasusClient.from_runtime()`` — it reads the two env
vars the tenant runner injects (``PEGASUS_API_BASE_URL`` /
``PEGASUS_RUNTIME_TOKEN``), so you never hardcode a base URL or token. A future
rename of those vars is then a one-line SDK fix, not a per-workflow break, and a
run outside the runner fails with a clear named error instead of a bare
``KeyError``.

    from pegasus_workflows import activity
    from pegasus_workflows.api import PegasusClient

    @activity.defn
    async def fetch_quote(quote_id: str) -> dict:
        client = PegasusClient.from_runtime()
        return client.get_workflow(quote_id)  # example — use the right method

## Input contract

See ``pegasus://guide/input-contract`` for the three argument shapes your
``run()`` method must handle (trigger-fired, manual run, CLI test).

## Secrets & configuration

To read per-tenant secrets or config at runtime, declare ``ReadWorkflowSecret``
/ ``ReadWorkflowConfig`` in your manifest ``required_actions`` and call
``client.get_secret(...)`` / ``client.get_config(...)`` inside an activity. See
``pegasus://guide/secrets-config`` for publishing and usage.

## Workflow diagram (required to publish)

Every workflow must ship a Mermaid diagram at ``<source_dir>/workflow.mmd``. The
tenant UI renders it so business users can confirm the workflow matches their
rules, and ``package`` / ``push`` fail without it. There is no AI service that
draws it for you — **you, the coding agent, draw it.** Call the ``diagram_prompt``
tool to get each workflow's source plus the exact output path and formatting
rules, produce a Mermaid ``flowchart TD`` that faithfully reflects the control
flow (no invented steps), and write it to the path the tool names.
``scaffold_workflow`` seeds a starter ``workflow.mmd`` so a fresh project already
publishes; refine it before publishing for real.
"""


def resource_guide_input_contract() -> str:
    """The three input shapes + a worked resolver example."""
    return """\
# Pegasus Workflow Input Contract

Your ``run()`` method receives a single positional argument. Its shape depends
on how the workflow was started:

## Shape 1 — Trigger-fired (domain-event trigger)

The dispatcher injects the full event envelope:

    {
        "domainEventId": "<uuid>",
        "eventType": "quote.accepted",
        "occurredAt": "<ISO-8601>",
        "payload": {"quoteId": "<id>", "moveId": "<id>"}
    }

Read ids from ``arg["payload"]["quoteId"]`` etc. The payload is a pointer,
not a snapshot — always re-fetch authoritative state from the Pegasus API.

## Shape 2 — Manual run

``POST /api/v1/workflows/:id/run`` passes:

    {"executionId": "<uuid>", "input": <user-supplied dict>}

Read your business data from ``arg["input"]``.

## Shape 3 — CLI test

``pegasus-workflows test <name>`` passes a raw string for local-dev parity.

## Shape 4 — Scheduled (cron trigger)

A SCHEDULE trigger (``pegasus-workflows schedule create``) fires on its cron
cadence, passing a tick envelope in the run input:

    {"executionId": "<uuid>",
     "input": {"scheduledAt": "<ISO-8601>", "schedule": "<cron>", "triggerId": "<id>"}}

Read it from ``arg["input"]``; detect a scheduled tick by the ``scheduledAt``
key. A tick carries no entity — the workflow does its own work (e.g. advance a
cursor and poll). It is distinct from a manual run, whose ``input`` is your own
business data.

## Recommended pattern: a module-level resolver (unit-testable)

Write a plain function — not a method — so it stays testable without a Temporal
worker context:

    def _resolve_quote_id(arg: dict | str) -> str:
        if isinstance(arg, str):
            return arg
        payload = arg.get("payload") if isinstance(arg, dict) else None
        if isinstance(payload, dict) and payload.get("quoteId"):
            return str(payload["quoteId"])
        inp = arg.get("input") if isinstance(arg, dict) else None
        if isinstance(inp, dict) and inp.get("scheduledAt"):
            return "scheduled-tick"        # Shape 4: a cron firing, no entity
        if isinstance(inp, dict) and inp.get("quote_id"):
            return str(inp["quote_id"])
        return "quote-unknown"
"""


def resource_guide_secrets_config() -> str:
    """How to publish and use per-tenant workflow secrets & configuration."""
    return """\
# Pegasus Workflow Secrets & Configuration

A workflow reads two kinds of per-tenant key/value data at runtime:

- **Secrets** — write-once, encrypted at rest, the plaintext is only ever handed
  to the workflow runtime (e.g. a third-party API key). Read action:
  ``ReadWorkflowSecret``.
- **Config** — plain, editable values (e.g. a region, a feature flag, a base URL).
  Read action: ``ReadWorkflowConfig``.

Both are scoped to the whole tenant: every workflow the tenant owns reads the
same namespace. A secret and a config entry may share a key — they are separate
namespaces.

## Organize with groups (recommended)

Every secret/config belongs to a **group** — a logical namespace for keeping
related keys together (e.g. ``billing``, ``notifications``, ``crm``). An entry
created without a group lands in ``global``.

**Best practice: put every key in a meaningful group; reserve ``global`` for
truly cross-cutting values.** Groups keep a growing store navigable and let you
list one area at a time. The group is part of an entry's identity, so the same
key may exist in different groups (e.g. ``API_KEY`` in both ``billing`` and
``crm``) — reads/writes must name the group (default ``global``). Groups are
organizational only; they are not an access-control boundary.

    pegasus-workflows secrets set STRIPE_API_KEY "sk_live_..." --group billing --token vnd_...
    pegasus-workflows secrets list --group billing --token vnd_...   # one group
    pegasus-workflows secrets list --token vnd_...                   # every group

    client.set_config("DEFAULT_REGION", "us-east-1", group="billing")
    region = client.get_config("DEFAULT_REGION", group="billing")

## 1. Declare what your workflow needs (manifest)

Add the read actions to ``required_actions`` in ``pegasus-workflows.toml`` so the
runtime service account is authorized to read them:

    [[workflow]]
    name = "send_quote_followup"
    version = "0.1.0"
    entry_points = ["send_quote_followup.workflow:SendQuoteFollowup"]
    required_actions = ["ReadQuote", "ReadWorkflowSecret", "ReadWorkflowConfig"]

## 2. Publish values (one-time, by a developer/admin)

Values are NOT part of the workflow artifact — publish them out of band with a
token holding ``ManageWorkflowSecrets`` / ``ManageWorkflowConfigs`` (the
``workflow_developer`` or ``tenant_admin`` role), via the CLI:

    pegasus-workflows secrets set STRIPE_API_KEY "sk_live_..." --token vnd_... --base-url https://api...
    pegasus-workflows config  set DEFAULT_REGION us-east-1   --token vnd_... --base-url https://api...
    pegasus-workflows secrets list --token vnd_...      # metadata only, never values
    pegasus-workflows config  list --token vnd_...

or from Python:

    client = PegasusClient(base_url="https://...", token="vnd_...")
    client.set_secret("STRIPE_API_KEY", "sk_live_...")
    client.set_config("DEFAULT_REGION", "us-east-1")

Secrets are **write-once** — to rotate, ``delete_secret`` then ``set_secret``
again. Config is an idempotent upsert (``set_config`` replaces the value).

## 3. Read values at runtime (inside an activity)

Read them with the runtime ``vnd_`` token inside an ``@activity.defn`` function —
never in workflow code (httpx is sandboxed there):

    from pegasus_workflows import activity
    from pegasus_workflows.api import PegasusClient

    @activity.defn
    async def charge_customer(amount_cents: int) -> str:
        client = PegasusClient.from_runtime()                       # runner's env contract
        api_key = client.get_secret("STRIPE_API_KEY", group="billing")  # needs ReadWorkflowSecret
        region = client.get_config("DEFAULT_REGION")                # group defaults to "global"
        ...

``get_secret`` / ``get_config`` take an optional ``group=`` (default ``"global"``)
and raise ``PegasusApiError`` with status 404 if the key is unset **in that group**
and 403 if the manifest did not declare the matching read action.
"""


def resource_reference_manifest() -> str:
    """Manifest reference generated from ``manifest.py`` constants at serve time."""
    field_lines = [f"- ``{f.name}``" for f in dataclasses.fields(Manifest)]
    return (
        "# Pegasus Manifest Reference\n\n"
        "Generated from ``pegasus_workflows.manifest`` — constants are read at\n"
        "serve time so this document stays in sync automatically.\n\n"
        "## File name\n\n"
        f"``{MANIFEST_FILENAME}``\n\n"
        "## Name constraint\n\n"
        f"Regex: ``{NAME_REGEX.pattern}``\n\n"
        "Lowercase letters, digits, ``_``, ``-``, 1–64 characters.\n\n"
        "## Version constraint\n\n"
        f"Regex: ``{VERSION_REGEX.pattern}``\n\n"
        "Semver subset: ``MAJOR.MINOR.PATCH`` with optional pre-release suffix\n"
        "(``-beta.1``, ``-rc.2``, ...).\n\n"
        "## Timeout constraint\n\n"
        f"``timeout_seconds`` max: ``{MANIFEST_TIMEOUT_MAX_SECONDS}`` s.\n"
        "The manifest may LOWER the platform default, never raise it.\n\n"
        "## Packaging requirement — workflow diagram\n\n"
        f"Every workflow must ship a Mermaid diagram at ``<source_dir>/{DIAGRAM_FILENAME}``.\n"
        "``package`` (and ``push``) hard-fail without it. Through MCP, call the\n"
        "``diagram_prompt`` tool to get each workflow's source + exact output path,\n"
        "draw the ``flowchart TD`` yourself, and write it to that path before\n"
        "``package_project``. ``scaffold_workflow`` seeds a starter diagram so a\n"
        "fresh project already packages.\n\n"
        "## Manifest fields (``Manifest`` dataclass)\n\n"
        + "\n".join(field_lines)
        + "\n\n"
        "## Example ``pegasus-workflows.toml``\n\n"
        "    [[workflow]]\n"
        '    name = "send_quote_followup"\n'
        '    version = "0.1.0"\n'
        '    entry_points = ["send_quote_followup.workflow:SendQuoteFollowup"]\n'
        '    source_dir = "send_quote_followup"   # optional, defaults to name\n'
        '    description = "Follow up on accepted quotes."\n'
        '    required_actions = ["ReadQuote", "EmitTenantEvent"]\n'
        "    timeout_seconds = 300\n"
    )


def resource_reference_api() -> str:
    """PegasusClient method surface, generated by introspection at serve time."""
    lines = [
        "# Pegasus API Reference (PegasusClient)",
        "",
        "Generated by introspecting ``pegasus_workflows.api.PegasusClient`` at serve",
        "time — adding or renaming a method or changing its docstring updates this",
        "resource automatically.",
        "",
    ]
    for name, method in inspect.getmembers(PegasusClient, predicate=inspect.isfunction):
        if name.startswith("_"):
            continue
        try:
            sig = inspect.signature(method)
            sig_str = f"{name}{sig}"
        except (ValueError, TypeError):
            sig_str = name
        doc = inspect.getdoc(method) or ""
        lines.append(f"## {sig_str}")
        if doc:
            lines.append("")
            lines.append(doc)
        lines.append("")
    return "\n".join(lines)


# ── Integration-config authoring guide + live discovery resources ───────────
# Everything an author (or AI agent) needs to publish an integration config —
# including the ingress `inbound` block — WITHOUT platform source.

_DEFAULT_API_ROOT = "https://api.pegasus.dolas.dev"


def _public_base_url() -> str:
    """Base URL for the public discovery endpoints (env override, else prod)."""
    import os

    return (os.environ.get("PEGASUS_BASE_URL") or _DEFAULT_API_ROOT).rstrip("/")


def _fetch_public(path: str) -> str | None:
    """GET a PUBLIC (no-auth) discovery endpoint; None if unreachable."""
    try:
        import httpx

        with httpx.Client(timeout=10.0) as client:
            response = client.get(f"{_public_base_url()}{path}")
            response.raise_for_status()
            return response.text
    except Exception:
        return None


def resource_reference_integration_config() -> str:
    """The full integration-config authoring guide (files, floors, rules, inbound, publish)."""
    return (
        "# Authoring & publishing an integration config\n\n"
        "An integration config is a published **overlay on a code-defined floor**. "
        "You author it as JSON files in a working directory and publish with the SDK/CLI. "
        "You never need platform source — discover the contract live (below).\n\n"
        "## Working-directory files\n\n"
        "- ``mapping.json`` (required) — native payload → canonical, output-shaped DSL. "
        "Schema: ``GET /api/v1/integrations/mapping-schema``.\n"
        "- ``rules.json`` (required) — behavioural rules (decision table). Ops: "
        "``eq, ne, gt, gte, lt, lte, in, nin``. Use ``nin`` for 'must be one of a set' "
        "(``{fact: brandPresent, op: eq, value: true}`` AND "
        "``{fact: brand, op: nin, value: [AVL,NVL]}``).\n"
        "- ``corpus.json`` (required) — gate cases: ``{input: {order: <native payload>}, "
        "expected: {valid, ruleIds}}``.\n"
        "- ``meta.json`` (optional) — ``{floor, displayName}``. **Required for a NEW id** "
        "with no built-in overlay: name the floor it builds on.\n"
        "- ``inbound.json`` (optional) — the ingress ack/validation block: "
        "``{eventType, dedupKeyPath, validation, ackTemplate}``. This is what makes an "
        "ingress return the partner's ack envelope (e.g. ADE "
        "``Result{Results:'Success'|'Failed', ResultsMessage:[...]}``) instead of the generic "
        "``{status:'accepted'}``. ``ackTemplate`` strings that are exactly ``{{key}}`` "
        "substitute a context value (``status``, ``errorCount``, ``messages``, ``issues``); "
        "``{\"$map\": \"issues\", \"as\": {...}}`` renders one element per issue. "
        "``validation`` = ``{requiredPaths, nonEmptyArrayPaths}`` (AND-checked), plus optional "
        "``oneOf`` — a list of variant shapes for a multi-shape partner (one ingress id that "
        "receives structurally different bodies, e.g. ADE Abstract vs Statement); the body must "
        "satisfy at least one. ``dedupKeyPath`` may be a list (first present path wins) so each "
        "variant dedups. Schema: ``GET /api/v1/integrations/inbound-schema``.\n"
        "- ``external-shape.json`` / ``external-mapping.json`` (optional) — partner OUTBOUND "
        "body shape + projection (only for send-to-partner integrations).\n\n"
        "## Discover the floor FIRST (so the gate accepts your files)\n\n"
        "A floor tells you the ONLY legal mapping *targets* (``canonicalFields``), rule "
        "*facts* (``factCatalog``), and — when declared — the legal mapping *source* roots a "
        "``$from`` may READ (``inputFieldRoots``: a bare entry opens a whole native root, a "
        "dotted entry like ``UnusedFields.survey_received`` opens ONLY that curated sub-path). "
        "Author against them:\n\n"
        "- ``client.list_floors()`` / ``client.get_floor(floor_id)`` (SDK), or\n"
        "- ``GET /api/v1/integrations/floors`` / ``/floors/{floorId}`` (public) — see the "
        "``pegasus://reference/floors`` resource for the live list.\n\n"
        "## Round-trip\n\n"
        "``pull`` (fetch an existing config to disk) → edit → ``validate`` (dry-run gate, "
        "no write) → ``publish`` (gate + write a new version).\n\n"
        "    pegasus-workflows integration-config validate <id> -C <dir>\n"
        "    pegasus-workflows integration-config publish  <id> -C <dir>\n\n"
        "SDK: ``client.validate_integration_config(id, mapping=, rules=, corpus=, floor=, "
        "inbound=, ...)`` then ``publish_integration_config(...)``.\n\n"
        "## Publishing gate\n\n"
        "Publishing GLOBAL needs the **platform tenant** + a ``vnd_`` key with the "
        "``PublishIntegrationConfig`` action, and the server's "
        "``INTEGRATION_CONFIG_PUBLISH_ENABLED`` switch on. "
        "``validate``/``pull`` are read-level.\n\n"
        "## Inspect the whole API\n\n"
        "The OpenAPI 3.1 spec is at ``GET /openapi.json`` (Swagger UI at ``/docs``) — see the "
        "``pegasus://reference/openapi`` resource. Combined with ``pegasus://reference/api`` "
        "(the PegasusClient method surface) and CLI ``--help``, that is the complete contract.\n"
    )


def resource_reference_floors() -> str:
    """Live list of built-in floors (canonicalFields + factCatalog + inputFieldRoots).

    Fetched from the API.
    """
    body = _fetch_public("/api/v1/integrations/floors")
    header = (
        "# Integration floors (live)\n\n"
        "Each floor is a per-type, partner-neutral contract. ``canonicalFields`` are the only "
        "legal mapping targets; ``factCatalog`` the only legal rule facts; ``inputFieldRoots`` "
        "(when present) the legal mapping source roots a ``$from`` may read — a bare entry opens "
        "a whole native root, a dotted entry opens only that curated sub-path. Author "
        "``mapping.json``/``rules.json`` against these. Also via ``client.get_floor(id)``.\n\n"
        f"Source: ``GET {_public_base_url()}/api/v1/integrations/floors``\n\n"
    )
    if body:
        return header + "```json\n" + body + "\n```\n"
    return header + (
        "_(Unreachable from this server — set ``PEGASUS_BASE_URL`` or call "
        "``client.list_floors()`` directly.)_\n"
    )


def resource_reference_openapi() -> str:
    """The API's OpenAPI 3.1 spec (live), so an agent can inspect every endpoint."""
    body = _fetch_public("/openapi.json")
    base = _public_base_url()
    header = (
        "# Pegasus API — OpenAPI 3.1 spec (live)\n\n"
        f"Live: ``GET {base}/openapi.json`` · Swagger UI: ``{base}/docs``\n\n"
        "Covers the SDK-facing (vnd_) surface (integrations authoring, workflows, "
        "documents, the operational read surface, …) incl. auth (vnd_ Bearer key) and "
        "request/response shapes. Any GET here is callable with no dedicated helper via "
        "``PegasusClient.api_get(path, **params)`` (read-only) — e.g. the paged/filtered "
        "projection read-model ``/integrations/{id}/projections/{entityType}``.\n\n"
    )
    if body:
        return header + "```json\n" + body + "\n```\n"
    return header + (
        "_(Unreachable from this server — set ``PEGASUS_BASE_URL`` and fetch ``/openapi.json`` "
        "directly.)_\n"
    )


# ── Tools (plain functions — no MCP runtime dependency) ──────────────────────


def tool_scaffold_workflow(name: str, dest: str) -> dict[str, Any]:
    """Scaffold a new workflow project at ``dest/name``.

    Wraps :func:`pegasus_workflows.cli.init.render_project`.

    Returns:
        ``{"ok": True, "project_dir": str, "files": [relative_path, ...]}``
        on success, or ``{"ok": False, "error": str}`` on failure.
    """
    dest_path = Path(dest).resolve()
    try:
        project_dir = render_project(name, dest_path)
    except (ValueError, FileExistsError, OSError) as exc:
        return {"ok": False, "error": str(exc)}

    files = sorted(
        str(p.relative_to(project_dir))
        for p in project_dir.rglob("*")
        if p.is_file()
    )
    return {"ok": True, "project_dir": str(project_dir), "files": files}


def tool_validate_manifest(path_or_toml: str) -> dict[str, Any]:
    """Validate a manifest file path or raw TOML text.

    Wraps :func:`pegasus_workflows.manifest.load_manifest`.  If *path_or_toml*
    resolves to an existing file, it is parsed directly.  Otherwise the value
    is treated as TOML text and written to a temporary file for parsing.

    Returns:
        ``{"ok": True, "manifests": [...]}`` on success, or
        ``{"ok": False, "error": str}`` on validation failure.
    """
    p = Path(path_or_toml)
    if p.is_file():
        try:
            manifests = load_manifest(p)
        except ManifestError as exc:
            return {"ok": False, "error": str(exc)}
        return {"ok": True, "manifests": [_manifest_to_dict(m) for m in manifests]}

    # Treat as raw TOML text.
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".toml", encoding="utf-8", delete=False
        ) as tmp:
            tmp_path = Path(tmp.name)  # assign before write so finally can always unlink
            tmp.write(path_or_toml)
        try:
            manifests = load_manifest(tmp_path)
        except ManifestError as exc:
            return {"ok": False, "error": str(exc)}
    except OSError as exc:
        # NamedTemporaryFile creation or write failed — return structured error.
        return {"ok": False, "error": f"could not create temporary file: {exc}"}
    finally:
        if tmp_path is not None:
            tmp_path.unlink(missing_ok=True)

    return {"ok": True, "manifests": [_manifest_to_dict(m) for m in manifests]}


def _manifest_to_dict(m: Manifest) -> dict[str, Any]:
    return {
        "name": m.name,
        "version": m.version,
        "entry_points": list(m.entry_points),
        "source_dir": m.source_dir,
        "description": m.description,
        "required_actions": list(m.required_actions),
        "timeout_seconds": m.timeout_seconds,
    }


def tool_diagram_prompt(project_dir: str, workflow: str | None = None) -> dict[str, Any]:
    """Build the bring-your-own-agent diagram prompt(s) for a project's workflows.

    Returns the same prompt the ``pegasus-workflows diagram`` CLI prints — each
    workflow's Python source plus the exact ``<source_dir>/workflow.mmd`` output
    path and Mermaid formatting rules — so the calling agent draws the
    ``flowchart TD`` itself and writes it to that path. A ``workflow.mmd`` is
    required to package/publish. Read-only: gathers source and returns text, no
    network and no write. Pass *workflow* to scope to a single workflow name.

    Returns:
        ``{"ok": True, "prompts": [{"workflow", "out_path", "exists", "prompt"}, ...]}``
        on success, or ``{"ok": False, "error": str}`` on failure.
    """
    proj = Path(project_dir).resolve()
    try:
        manifests = load_manifest(proj)
    except ManifestError as exc:
        return {"ok": False, "error": str(exc)}

    if workflow is not None:
        manifests = [m for m in manifests if m.name == workflow]
        if not manifests:
            return {"ok": False, "error": f"no workflow named {workflow!r} in this project"}

    prompts: list[dict[str, Any]] = []
    for m in manifests:
        source_dir = proj / m.source_dir
        if not source_dir.is_dir():
            return {
                "ok": False,
                "error": f"workflow {m.name}: source_dir '{m.source_dir}' not found",
            }
        out_path = f"{m.source_dir}/{DIAGRAM_FILENAME}"
        prompts.append(
            {
                "workflow": m.name,
                "out_path": out_path,
                "exists": (source_dir / DIAGRAM_FILENAME).is_file(),
                "prompt": build_diagram_prompt(m.name, out_path, gather_source(source_dir)),
            }
        )
    return {"ok": True, "prompts": prompts}


def tool_package_project(project_dir: str) -> dict[str, Any]:
    """Package every workflow declared in ``project_dir`` into ``dist/``.

    Wraps :func:`pegasus_workflows.cli.package.package_project`.

    Returns:
        ``{"ok": True, "artifacts": [{name, version, zip_path, size_bytes}, ...]}``
        on success, or ``{"ok": False, "error": str}`` on failure.
    """
    try:
        results = _pkg_project(Path(project_dir).resolve())
    except (ManifestError, OSError) as exc:
        # The missing-diagram failure names a shell command (`pegasus-workflows
        # diagram`) that an MCP-only agent can't run. Rewrite the remedy to the
        # in-MCP path so scaffold → (draw) → package stays reachable without a
        # shell. See the `diagram_prompt` tool + pegasus://reference/manifest.
        message = str(exc)
        if DIAGRAM_FILENAME in message:
            return {
                "ok": False,
                "error": message,
                "remedy": (
                    f"A workflow diagram ({DIAGRAM_FILENAME}) is required to package. "
                    "Call the `diagram_prompt` tool to get each workflow's source and "
                    "output path, draw the Mermaid `flowchart TD` yourself, write it to "
                    "the path the tool names, then call `package_project` again."
                ),
            }
        return {"ok": False, "error": message}

    artifacts = [
        {
            "name": manifest.name,
            "version": manifest.version,
            "zip_path": str(zip_path),
            "size_bytes": zip_path.stat().st_size,
        }
        for manifest, zip_path in results
    ]
    return {"ok": True, "artifacts": artifacts}


def tool_validate_integration_config(
    integration_id: str,
    mapping: Any,
    rules: Any,
    corpus: Any,
    base_url: str,
    token: str,
    floor: str | None = None,
    inbound: Any | None = None,
) -> dict[str, Any]:
    """Dry-run the integration config publish gate. No write.

    Constructs a :class:`~pegasus_workflows.api.PegasusClient` from *base_url*
    and *token*, then calls
    :meth:`~pegasus_workflows.api.PegasusClient.validate_integration_config`.
    Pass *floor* for a new id with no built-in overlay, and *inbound* to gate the
    ingress ack/validation block too.

    Returns:
        ``{"ok": True, "report": {...}}`` on success, or
        ``{"ok": False, "error": str}`` on failure.
    """
    client = PegasusClient(base_url=base_url, token=token)
    try:
        report = client.validate_integration_config(
            integration_id,
            mapping=mapping,
            rules=rules,
            corpus=corpus,
            floor=floor,
            inbound=inbound,
        )
        return {"ok": True, "report": report}
    except Exception as exc:  # broad catch: httpx, PegasusApiError, network errors
        return {"ok": False, "error": str(exc)}


def tool_list_deployments(project_dir: str) -> dict[str, Any]:
    """Read a project's ``deployments.toml`` ledger. Read-only — no network, no write.

    Wraps :func:`pegasus_workflows.deployments.read_deployments`, so an agent can
    answer "where is this deployed / what's its id in env X" without scraping
    terminal output.

    Returns:
        ``{"ok": True, "deployments": {...}}`` (empty dict when no ledger exists),
        or ``{"ok": False, "error": str}`` on a malformed file.
    """
    try:
        deployments = read_deployments(Path(project_dir).resolve())
    except (OSError, ValueError) as exc:
        return {"ok": False, "error": str(exc)}
    return {"ok": True, "deployments": deployments}


def tool_list_profiles() -> dict[str, Any]:
    """List credential profile names + api_root. **Never** returns ``api_key``.

    Wraps :func:`pegasus_workflows.credentials.list_profile_summaries`. Secrets
    must not cross the MCP boundary, so only names and api_roots are exposed.

    Returns:
        ``{"ok": True, "profiles": [{"name", "api_root"}, ...]}`` or
        ``{"ok": False, "error": str}``.
    """
    try:
        return {"ok": True, "profiles": list_profile_summaries()}
    except ProfileError as exc:
        return {"ok": False, "error": str(exc)}


# ── MCP server builder ────────────────────────────────────────────────────────


def _build_server(FastMCP: type) -> Any:  # type: ignore[type-arg]
    """Wire resources and tools onto a fresh FastMCP instance.

    Receives the FastMCP class as an argument so the caller controls when
    the ``mcp`` library is imported and tests can wire it without starting
    a real stdio loop.
    """
    server = FastMCP(
        "pegasus-workflows",
        instructions=(
            "Use the resources to understand Pegasus workflow authoring rules "
            "and the tools to scaffold, validate, package, and dry-run-gate "
            "workflows without triggering any network writes."
        ),
    )

    @server.resource("pegasus://guide/authoring")
    def _res_guide_authoring() -> str:
        return resource_guide_authoring()

    @server.resource("pegasus://guide/input-contract")
    def _res_guide_input_contract() -> str:
        return resource_guide_input_contract()

    @server.resource("pegasus://guide/secrets-config")
    def _res_guide_secrets_config() -> str:
        return resource_guide_secrets_config()

    @server.resource("pegasus://reference/manifest")
    def _res_reference_manifest() -> str:
        return resource_reference_manifest()

    @server.resource("pegasus://reference/api")
    def _res_reference_api() -> str:
        return resource_reference_api()

    @server.resource("pegasus://reference/integration-config")
    def _res_reference_integration_config() -> str:
        return resource_reference_integration_config()

    @server.resource("pegasus://reference/floors")
    def _res_reference_floors() -> str:
        return resource_reference_floors()

    @server.resource("pegasus://reference/openapi")
    def _res_reference_openapi() -> str:
        return resource_reference_openapi()

    @server.tool()
    def scaffold_workflow(name: str, dest: str) -> dict:  # type: ignore[type-arg]
        """Scaffold a new workflow project at dest/name (wraps pegasus-workflows init)."""
        return tool_scaffold_workflow(name, dest)

    @server.tool()
    def validate_manifest(path_or_toml: str) -> dict:  # type: ignore[type-arg]
        """Validate a manifest file path or raw TOML text."""
        return tool_validate_manifest(path_or_toml)

    @server.tool()
    def diagram_prompt(project_dir: str, workflow: str | None = None) -> dict:  # type: ignore[type-arg]
        """Build the BYO-agent prompt(s) for drawing each workflow.mmd (read-only, no network)."""
        return tool_diagram_prompt(project_dir, workflow)

    @server.tool()
    def package_project(project_dir: str) -> dict:  # type: ignore[type-arg]
        """Package every workflow in project_dir into dist/ (wraps pegasus-workflows package)."""
        return tool_package_project(project_dir)

    @server.tool()
    def validate_integration_config(
        integration_id: str,
        mapping: Any,
        rules: Any,
        corpus: Any,
        base_url: str,
        token: str,
        floor: str | None = None,
        inbound: Any | None = None,
    ) -> dict:  # type: ignore[type-arg]
        """Dry-run the integration config publish gate (incl. floor + inbound). No write."""
        return tool_validate_integration_config(
            integration_id, mapping, rules, corpus, base_url, token, floor, inbound
        )

    @server.tool()
    def list_deployments(project_dir: str) -> dict:  # type: ignore[type-arg]
        """Read a project's deployments.toml ledger (read-only — no network)."""
        return tool_list_deployments(project_dir)

    @server.tool()
    def list_profiles() -> dict:  # type: ignore[type-arg]
        """List credential profile names + api_root — never a key (read-only)."""
        return tool_list_profiles()

    return server


# ── Typer command ─────────────────────────────────────────────────────────────


def mcp_command() -> None:
    """Start a stdio MCP server for AI coding agents.

    Exposes SDK resources and safe tools so any MCP-compatible agent can
    scaffold, validate, and package Pegasus workflows without network side
    effects.  Network-mutating operations (push, publish, run) are not exposed
    and remain human-gated via the CLI.

    The MCP dependency ships in the base package — a plain
    ``pip install pegasus-workflows-sdk`` is enough.
    """
    try:
        from mcp.server.fastmcp import FastMCP
    except ImportError:
        typer.secho(_MISSING_EXTRA_MSG, fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from None

    server = _build_server(FastMCP)
    server.run("stdio")
