#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Full-stack deployment for Pegasus
#
# CDK resolves cross-stack references automatically via Fn::ImportValue, so a
# single `cdk deploy --all` is sufficient. CloudFormation determines deployment
# order from the dependency graph:
#
#   1. FrontendStack + AdminFrontendStack (parallel)
#   2. CognitoStack
#   3. ApiStack
#   4. FrontendAssetsStack + AdminFrontendAssetsStack (parallel)
#
# Usage:
#   ./deploy.sh                  # deploy everything (default)
#   ./deploy.sh --dry-run        # print all commands without executing them
#   ./deploy.sh --api-only       # deploy API + infra stacks only (skips asset stacks)
#   ./deploy.sh --admin-only     # build + deploy admin frontend stacks only
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INFRA_DIR="$REPO_ROOT/packages/infra"
OUTPUTS_FILE="/tmp/pegasus-cdk-outputs.json"

# All CDK commands run from the infra directory.
cd "$INFRA_DIR"

AWS_PROFILE="${AWS_PROFILE:-admin-dev}"
API_ONLY=false
ADMIN_ONLY=false
DRY_RUN=false

for arg in "$@"; do
  [[ "$arg" == "--api-only" ]]   && API_ONLY=true
  [[ "$arg" == "--admin-only" ]] && ADMIN_ONLY=true
  [[ "$arg" == "--dry-run" ]]    && DRY_RUN=true
done

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

run() {
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│         Pegasus — Full-Stack Deployment          │"
echo "└─────────────────────────────────────────────────┘"
if [[ "$DRY_RUN" == "true" ]]; then
  echo "  (dry-run mode — no AWS calls or file writes)"
fi
echo ""

# ── 1. Build frontends ────────────────────────────────────────────────────────
# Builds happen before CDK deploy; no URLs are needed at build time since
# runtime config is generated by the assets stacks via Source.jsonData.
if [[ "$API_ONLY" == "false" ]]; then
  if [[ "$ADMIN_ONLY" == "false" ]]; then
    echo "▶  [1/2] Building web package..."
    run npm run build --workspace=@pegasus/tenant-web --prefix "$REPO_ROOT"
  fi
  echo "▶  [1/2] Building apps/admin-web..."
  run npm run build --workspace=@pegasus/admin-web --prefix "$REPO_ROOT"
fi

# ── 2. Deploy — CDK resolves ordering from the dependency graph ───────────────
# Stacks selected by flag:
#   (default)      --all
#   --api-only     infra + cognito + api stacks (asset stacks skipped)
#   --admin-only   admin infra + cognito + api + admin assets stack

if [[ "$API_ONLY" == "true" ]]; then
  DEPLOY_TARGET="PegasusDev-FrontendStack PegasusDev-AdminFrontendStack PegasusDev-CognitoStack PegasusDev-ApiStack"
  echo "▶  [2/2] Deploying API stacks (infra + cognito + api)..."
elif [[ "$ADMIN_ONLY" == "true" ]]; then
  DEPLOY_TARGET="PegasusDev-AdminFrontendStack PegasusDev-CognitoStack PegasusDev-ApiStack PegasusDev-AdminFrontendAssetsStack"
  echo "▶  [2/2] Deploying admin stacks..."
else
  DEPLOY_TARGET="--all"
  echo "▶  [2/2] Deploying all stacks..."
fi

# shellcheck disable=SC2086
run npx cdk deploy $DEPLOY_TARGET \
  --profile "$AWS_PROFILE" \
  --require-approval never \
  --outputs-file "$OUTPUTS_FILE" \
  --app "npx tsx bin/app.ts"

echo ""
echo "✔  Deployment complete!"
echo ""

if [[ "$DRY_RUN" == "false" && -f "$OUTPUTS_FILE" ]]; then
  WEB_URL=$(jq -r '.["pegasus-dev-frontend"].DistributionUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)
  ADMIN_URL=$(jq -r '.["pegasus-dev-admin-frontend"].AdminDistributionUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)
  API_URL=$(jq -r '.["pegasus-dev-api"].ApiUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)

  [[ -n "$WEB_URL" ]]   && echo "   Client app:      $WEB_URL"
  [[ -n "$ADMIN_URL" ]] && echo "   Admin portal:    $ADMIN_URL"
  [[ -n "$API_URL" ]]   && echo "   API:             $API_URL"
fi
echo ""
