#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Local/emergency deploy wrapper for Pegasus
#
# CI/CD (.github/workflows/deploy.yml) is the canonical deploy path. This
# script exists for local emergency deploys when CI is unavailable. It shells
# out to `npm run deploy:ci` from packages/infra so both paths run the exact
# same CDK command.
#
# Usage:
#   ./deploy.sh                  # deploy everything (default)
#   ./deploy.sh --api-only       # deploy API + infra stacks only
#   ./deploy.sh --admin-only     # build + deploy admin frontend stacks only
#   ./deploy.sh --dry-run        # print the commands without executing them
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INFRA_DIR="$REPO_ROOT/packages/infra"
OUTPUTS_FILE="/tmp/pegasus-cdk-outputs.json"

cd "$INFRA_DIR"

AWS_PROFILE="${AWS_PROFILE:-admin-dev}"
export AWS_PROFILE

API_ONLY=false
ADMIN_ONLY=false
DRY_RUN=false

for arg in "$@"; do
  [[ "$arg" == "--api-only" ]]   && API_ONLY=true
  [[ "$arg" == "--admin-only" ]] && ADMIN_ONLY=true
  [[ "$arg" == "--dry-run" ]]    && DRY_RUN=true
done

run() {
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [dry-run] $*"
  else
    "$@"
  fi
}

echo ""
echo "┌─────────────────────────────────────────────────┐"
echo "│    Pegasus — Local Deploy (CI is canonical)      │"
echo "└─────────────────────────────────────────────────┘"
if [[ "$DRY_RUN" == "true" ]]; then
  echo "  (dry-run mode — no AWS calls or file writes)"
fi
echo ""

# ── 1. Build frontends ────────────────────────────────────────────────────────
if [[ "$API_ONLY" == "false" ]]; then
  if [[ "$ADMIN_ONLY" == "false" ]]; then
    echo "▶  [1/2] Building @pegasus/tenant-web..."
    run npm run build --workspace=@pegasus/tenant-web --prefix "$REPO_ROOT"
  fi
  echo "▶  [1/2] Building @pegasus/admin-web..."
  run npm run build --workspace=@pegasus/admin-web --prefix "$REPO_ROOT"
fi

# ── 2. Resolve TARGET (mirror deploy.yml's mapping) ───────────────────────────
if [[ "$API_ONLY" == "true" ]]; then
  TARGET="PegasusDev-FrontendStack PegasusDev-AdminFrontendStack PegasusDev-CognitoStack PegasusDev-DocumentsStack PegasusDev-WireGuardStack PegasusDev-ApiStack PegasusDev-MonitoringStack"
  echo "▶  [2/2] Deploying API stacks..."
elif [[ "$ADMIN_ONLY" == "true" ]]; then
  TARGET="PegasusDev-AdminFrontendStack PegasusDev-CognitoStack PegasusDev-ApiStack PegasusDev-AdminFrontendAssetsStack"
  echo "▶  [2/2] Deploying admin stacks..."
else
  TARGET="--all"
  echo "▶  [2/2] Deploying all stacks..."
fi

export TARGET
run npm run deploy:ci

echo ""
echo "✔  Deployment complete!"
echo ""

# ── 3. Print URLs + generate mobile .env.deploy ───────────────────────────────
if [[ "$DRY_RUN" == "false" && -f "$OUTPUTS_FILE" ]]; then
  WEB_URL=$(jq -r '.["pegasus-dev-frontend"].DistributionUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)
  ADMIN_URL=$(jq -r '.["pegasus-dev-admin-frontend"].AdminDistributionUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)
  API_URL=$(jq -r '.["pegasus-dev-api"].ApiUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)

  [[ -n "$WEB_URL" ]]   && echo "   Client app:      $WEB_URL"
  [[ -n "$ADMIN_URL" ]] && echo "   Admin portal:    $ADMIN_URL"
  [[ -n "$API_URL" ]]   && echo "   API:             $API_URL"

  COGNITO_USER_POOL_ID=$(jq -r '.["pegasus-dev-cognito"].UserPoolId // empty' "$OUTPUTS_FILE" 2>/dev/null || true)
  COGNITO_MOBILE_CLIENT_ID=$(jq -r '.["pegasus-dev-cognito"].MobileClientId // empty' "$OUTPUTS_FILE" 2>/dev/null || true)
  COGNITO_HOSTED_UI_DOMAIN=$(jq -r '.["pegasus-dev-cognito"].HostedUiBaseUrl // empty' "$OUTPUTS_FILE" 2>/dev/null || true)

  MOBILE_ENV_FILE="$REPO_ROOT/apps/mobile/.env.deploy"

  if [[ -n "$API_URL" && -n "$COGNITO_USER_POOL_ID" && -n "$COGNITO_MOBILE_CLIENT_ID" ]]; then
    cat > "$MOBILE_ENV_FILE" <<ENVEOF
# Generated by deploy.sh — do not edit manually
EXPO_PUBLIC_API_URL=$API_URL
EXPO_PUBLIC_COGNITO_REGION=us-east-1
EXPO_PUBLIC_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
EXPO_PUBLIC_COGNITO_CLIENT_ID=$COGNITO_MOBILE_CLIENT_ID
EXPO_PUBLIC_COGNITO_DOMAIN=$COGNITO_HOSTED_UI_DOMAIN
EXPO_PUBLIC_COGNITO_REDIRECT_URI=movingapp://auth/callback
ENVEOF
    echo "   Mobile .env:     $MOBILE_ENV_FILE"
  fi
fi
echo ""
