import { empty, eqNum, eq, static_ } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const billingEntities: EntityConfig[] = [
  {
    slug: 'invoices',
    tableName: 'invoice',
    idField: 'invoice_num',
    codeField: 'invoice_num',
    idType: 'integer',
    orderBy: 'ORDER BY invoice_num DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'invoice_num'),
      eqNum('CODE', 'invoice_num'),
      eqNum('INVOICENUM', 'invoice_num'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('ORDERNUMBER', 'order_num'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'invoice-masters',
    tableName: 'invoicemaster',
    idField: 'invoice_num',
    codeField: 'invoice_num',
    idType: 'integer',
    orderBy: 'ORDER BY invoice_num DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'invoice_num'),
      eqNum('CODE', 'invoice_num'),
      eqNum('INVOICENUM', 'invoice_num'),
      eqNum('ORDERNUM', 'order_num'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'invoice-details',
    tableName: 'invoicedetail',
    idField: 'Id',
    codeField: 'Id',
    idType: 'integer',
    orderBy: 'ORDER BY Id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'Id'),
      eqNum('INVOICENUM', 'invoice_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
  {
    slug: 'billing-codes',
    tableName: 'billingcodes',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'code'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
    freeTextColumns: ['description', 'code'],
  },
  {
    slug: 'services',
    tableName: 'Services',
    idField: 'Id',
    codeField: 'service_id',
    idType: 'integer',
    orderBy: 'ORDER BY service_id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'Id'),
      eq('CODE', 'service_id'),
      eq('SERVICEID', 'service_id'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
    freeTextColumns: ['description', 'service_id'],
  },
]
