import { empty, eqNum, eq, like, static_ } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const driverEntities: EntityConfig[] = [
  {
    slug: 'drivers',
    tableName: 'drivers',
    idField: 'id',
    codeField: 'driver_id',
    idType: 'integer',
    orderBy: 'ORDER BY driver_name',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'driver_id'),
      eq('DRIVERID', 'driver_id'),
      like('NAME', 'driver_name'),
      eq('BRANCH', 'branch'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
    freeTextColumns: ['driver_name', 'driver_id'],
  },
  {
    slug: 'settlements',
    tableName: 'settlements',
    idField: 'settlement_num',
    codeField: 'settlement_num',
    idType: 'integer',
    orderBy: 'ORDER BY settlement_num DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'settlement_num'),
      eqNum('CODE', 'settlement_num'),
      eq('DRIVERID', 'driver_id'),
      eq('DRIVER', 'driver_id'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'settlement-masters',
    tableName: 'settlementmaster',
    idField: 'settlement_num',
    codeField: 'settlement_num',
    idType: 'integer',
    orderBy: 'ORDER BY settlement_num DESC',
    searchKeywords: [empty(), eqNum('ID', 'settlement_num'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'settlement-details',
    tableName: 'settlementdetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('SETTLEMENTNUM', 'settlement_num')],
  },
  {
    slug: 'settlement-codes',
    tableName: 'settlementcodes',
    idField: 'id',
    codeField: 'rvs_num',
    idType: 'integer',
    orderBy: 'ORDER BY rvs_num',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'rvs_num'),
      static_('ACTIVE', "active='Y'"),
    ],
  },
  {
    slug: 'master-settlement-details',
    tableName: 'mastersettlements',
    idField: 'id',
    codeField: 'data_edit_seq',
    idType: 'integer',
    orderBy: 'ORDER BY data_edit_seq',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'data_edit_seq')],
  },
  {
    slug: 'master-settlement-buckets',
    tableName: 'masterstlmtbuckets',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'debits',
    tableName: 'debit',
    idField: 'debit_num',
    codeField: 'debit_num',
    idType: 'integer',
    orderBy: 'ORDER BY debit_num DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'debit_num'),
      eqNum('CODE', 'debit_num'),
      eq('DRIVERID', 'driver_id'),
      eq('DRIVER', 'driver_id'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'debit-history',
    tableName: 'dh_debit',
    idField: 'debit_num',
    codeField: 'debit_num',
    idType: 'integer',
    orderBy: 'ORDER BY debit_num DESC',
    searchKeywords: [empty(), eqNum('ID', 'debit_num'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'retainers',
    tableName: 'retainer',
    idField: 'driver_id',
    codeField: 'driver_id',
    idType: 'string',
    orderBy: 'ORDER BY driver_id',
    searchKeywords: [empty(), eq('DRIVERID', 'driver_id'), eq('CODE', 'driver_id')],
  },
  {
    slug: 'begin-month-balances',
    tableName: 'drvbal',
    idField: 'daily_id',
    codeField: 'daily_id',
    idType: 'integer',
    orderBy: 'ORDER BY daily_id DESC',
    searchKeywords: [empty(), eqNum('ID', 'daily_id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'monthly-balances-this-year',
    tableName: 'drvhist',
    idField: 'daily_id',
    codeField: 'daily_id',
    idType: 'integer',
    orderBy: 'ORDER BY daily_id DESC',
    searchKeywords: [empty(), eqNum('ID', 'daily_id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'monthly-balances-prior-years',
    tableName: 'dh_bal',
    idField: 'daily_id',
    codeField: 'daily_id',
    idType: 'integer',
    orderBy: 'ORDER BY daily_id DESC',
    searchKeywords: [empty(), eqNum('ID', 'daily_id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'monthly-debits-credits-this-year',
    tableName: 'driverytd',
    idField: 'id',
    codeField: 'ytd_id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'monthly-debits-credits-prior-years',
    tableName: 'dh_ytd',
    idField: 'id',
    codeField: 'ytd_id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'driver-monthly-balance',
    tableName: 'DriverYTDSummary',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'driver-logs',
    tableName: 'drlog',
    idField: 'id',
    codeField: 'rvs_num',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'rvs_num'),
      eq('DRIVERID', 'driver_id'),
    ],
  },
  {
    slug: 'driver-settlement-paperwork-log',
    tableName: 'drlog',
    idField: 'drlog_num',
    codeField: 'drlog_num',
    idType: 'integer',
    orderBy: 'ORDER BY drlog_num DESC',
    searchKeywords: [empty(), eqNum('ID', 'drlog_num'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'expense-codes',
    tableName: 'drvexpensecodes',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'code'),
      static_('ACTIVE', "active='Y'"),
    ],
    freeTextColumns: ['description', 'code'],
  },
  {
    slug: 'units',
    tableName: 'units',
    idField: 'id',
    codeField: 'rvs_num',
    idType: 'integer',
    orderBy: 'ORDER BY rvs_num',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'rvs_num'),
      eq('RVSNUM', 'rvs_num'),
      eq('DRIVERID', 'driver_id'),
      static_('ACTIVE', "active='Y'"),
    ],
  },
  {
    slug: 'comdata',
    tableName: 'comdata',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'settlement-from-atlas',
    tableName: 'settlement_from_atlas',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'driver-commission-by-miles-weight',
    tableName: 'DriverCommissionByMilesAndWeight',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('DRIVERID', 'driver_id')],
  },
  {
    slug: 'master-driver-ytd-summary-fields',
    tableName: 'MasterDriverYTDSummaryCodes',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [eqNum('ID', 'id')],
  },
]
