import { empty, eqNum, eq } from '../keyword-helpers'
import type { EntityConfig, SqlFragment } from '../types'

export const mastersEntities: EntityConfig[] = [
  {
    slug: 'master-email-templates',
    tableName: 'MasterEMailTemplates',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'master-schedules',
    tableName: 'masterschedules',
    idField: 'id',
    codeField: 'number',
    idType: 'integer',
    orderBy: 'ORDER BY number',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'number')],
  },
  {
    slug: 'master-currencies',
    tableName: 'mastercurrencies',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'master-shipment-types',
    tableName: 'mastershipmentypes',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'master-comments',
    tableName: 'mastercomments',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      {
        keyword: 'TYPE',
        toSql: (p, paramId): SqlFragment => {
          const id = paramId()
          return { sql: `type=@${id}`, params: { [id]: p } }
        },
      },
    ],
  },
  {
    slug: 'driver-pay-groups',
    tableName: 'DriverPayGroups',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'master-transportation-modes',
    tableName: 'mastertranspomodes',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'master-reports',
    tableName: 'MasterReports',
    idField: 'id',
    codeField: 'number',
    idType: 'integer',
    orderBy: 'ORDER BY number',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'number')],
  },
  {
    slug: 'master-materials',
    tableName: 'mastermaterials',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'master-insurance-types',
    tableName: 'masterinsurancetypes',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'master-premium-service-details',
    tableName: 'masterpremiumservicedetail',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
]
