import { empty, eqNum, eq, static_ } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const premiumServicesEntities: EntityConfig[] = [
  {
    slug: 'premium-service-details',
    tableName: 'PremiumServiceDetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('SALE', 'order_num'),
      eq('ACCOUNT', 'account_code'),
      eqNum('MASTER', 'master_id'),
      eqNum('3RDPARTY', 'third_party_id'),
      eq('STATUS', 'status'),
      eq('AT', 'at_code'),
      eq('SOURCE', 'source'),
      eq('ON', 'service_date'),
    ],
  },
  {
    slug: 'account-premium-service-details',
    tableName: 'accountpremiumservicedetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('ACCOUNT', 'account_code')],
  },
  {
    slug: 'master-account-authorizations',
    tableName: 'MasterAccountAuthorizations',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'third-party-service-providers',
    tableName: 'ThirdPartyServiceProviders',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'third-party-service-orders',
    tableName: 'ThirdPartyServiceOrders',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'shipper-addresses',
    tableName: 'ShipperAddresses',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'shipper-vehicles',
    tableName: 'ShipperVehicles',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
]
