import { eqNum, eq, like, static_ } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const sharedEntities: EntityConfig[] = [
  {
    slug: 'settings',
    tableName: 'settings',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY name, id',
    listFields: 'active, name, value, type, scope, id AS code, id',
    searchKeywords: [
      eqNum('ID', 'id'),
      eqNum('CODE', 'id'),
      eq('NAME', 'name'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'branches',
    tableName: 'branches',
    idField: 'id',
    codeField: 'branch_id',
    idType: 'integer',
    orderBy: 'ORDER BY branch_name',
    listFields:
      'branch_active, branch_id, branch_name, agency_code, branch_street_adr, branch_csz, branch_phone1, company_id, branch_id AS code, id',
    searchKeywords: [
      eqNum('ID', 'id'),
      eq('CODE', 'branch_id'),
      eq('BRANCHID', 'branch_id'),
      eq('BRANCHCODE', 'branch_id'),
      eq('COMPANYID', 'company_id'),
      eq('COMPANYCODE', 'company_id'),
      eq('AGENTID', 'agency_code'),
      eq('AGENTCODE', 'agency_code'),
      eq('AGENCYCODE', 'agency_code'),
      static_('ACTIVE', "branch_active='Y'"),
      static_('NOTACTIVE', "branch_active='N'"),
    ],
  },
  {
    slug: 'states',
    tableName: 'states',
    idField: 'id',
    codeField: 'state_code',
    idType: 'integer',
    orderBy: 'ORDER BY state_name',
    searchKeywords: [eqNum('ID', 'id'), eq('CODE', 'state_code'), like('NAME', 'state_name')],
  },
  {
    slug: 'zip-codes',
    tableName: 'zip_codes',
    idField: 'id',
    codeField: 'zip_code',
    idType: 'integer',
    orderBy: 'ORDER BY zip_code',
    searchKeywords: [
      eqNum('ID', 'id'),
      eq('CODE', 'zip_code'),
      eq('ZIP', 'zip_code'),
      like('CITY', 'city'),
      eq('STATE', 'state'),
    ],
  },
  {
    slug: 'move-types',
    tableName: 'move_types',
    idField: 'id',
    codeField: 'move_type_code',
    idType: 'integer',
    orderBy: 'ORDER BY description',
    searchKeywords: [
      eqNum('ID', 'id'),
      eq('CODE', 'move_type_code'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'bdo-codes',
    tableName: 'bdo_codes',
    idField: 'id',
    codeField: 'bdo_code',
    idType: 'integer',
    orderBy: 'ORDER BY description',
    searchKeywords: [
      eqNum('ID', 'id'),
      eq('CODE', 'bdo_code'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'postal-addresses',
    tableName: 'postal_addresses',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      eqNum('ID', 'id'),
      like('CITY', 'city'),
      eq('STATE', 'state'),
      eq('ZIP', 'zip_code'),
    ],
  },
]
