import { empty, eqNum, eq } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const unsortedEntities: EntityConfig[] = [
  {
    slug: 'ats-instructions',
    tableName: 'ATS',
    idField: 'id',
    codeField: 'AgentID',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'AgentID')],
  },
  {
    slug: 'atlas-dispatch',
    tableName: 'Sudsresultsstops',
    idField: 'id',
    codeField: 'order_number',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('CODE', 'order_number'),
      eqNum('ORDERNUM', 'order_number'),
    ],
  },
  {
    slug: 'dispatch-logs',
    tableName: 'dispatch_log',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'drivers-long-dist',
    tableName: 'drivers_long_dist',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY code',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'code')],
  },
  {
    slug: 'insurance-companies',
    tableName: 'insurance',
    idField: 'id',
    codeField: 'under_code',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'under_code')],
  },
  {
    slug: 'crate-masters',
    tableName: 'cratemaster',
    idField: 'serial_num',
    codeField: 'serial_num',
    idType: 'string',
    orderBy: 'ORDER BY serial_num',
    searchKeywords: [empty(), eq('ID', 'serial_num'), eq('CODE', 'serial_num')],
  },
  {
    slug: 'crate-details',
    tableName: 'CrateDetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'sale-crew-history',
    tableName: 'sales_crewhistory',
    idField: 'id',
    codeField: 'order_num',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('CODE', 'order_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
]
