import { empty, eqNum, eq } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const warehouseEntities: EntityConfig[] = [
  {
    slug: 'hhg-storage-masters',
    tableName: 'hhgstoragemaster',
    idField: 'id',
    codeField: 'order_number',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('CODE', 'order_number'),
      eqNum('ORDERNUM', 'order_number'),
    ],
  },
  {
    slug: 'hhg-storage-details',
    tableName: 'hhgstoragedetail',
    idField: 'id',
    codeField: 'stg_unit_code',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'stg_unit_code')],
  },
  {
    slug: 'hhg-storage-units',
    tableName: 'boxmaster',
    idField: 'id',
    codeField: 'box_order',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'box_order')],
  },
  {
    slug: 'storage-units',
    tableName: 'box',
    idField: 'id',
    codeField: 'box_code',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'box_code'),
      eq('BRANCH', 'branch'),
      eq('STATUS', 'box_status'),
      eq('SITE', 'site'),
    ],
  },
  {
    slug: 'storage-unit-history',
    tableName: 'boxlog',
    idField: 'id',
    codeField: 'box_code',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eq('CODE', 'box_code')],
  },
  {
    slug: 'commercial-warehouse-masters',
    tableName: 'comm_m',
    idField: 'id',
    codeField: 'order_num',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('CODE', 'order_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
  {
    slug: 'commercial-warehouse-details',
    tableName: 'comm_d',
    idField: 'eticket',
    codeField: 'eticket',
    idType: 'integer',
    orderBy: 'ORDER BY eticket',
    searchKeywords: [empty(), eqNum('ID', 'eticket'), eqNum('CODE', 'eticket')],
  },
  {
    slug: 'commercial-warehouse-etickets',
    tableName: 'comm_eticket',
    idField: 'id',
    codeField: 'order_num',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('CODE', 'order_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
]
