// OpenAPI 3.1.0 spec for Pegasus API — served at GET /openapi.json

export type OpenApiDocument = {
  openapi: string
  info: { title: string; version: string; description?: string }
  paths: Record<string, Record<string, unknown>>
  components?: Record<string, unknown>
}

const ref = (schema: string) => ({ ["$ref"]: schema })

export const openapiSpec: OpenApiDocument = {
  openapi: "3.1.0",
  info: { title: "Pegasus API", version: "1.0.0", description: "Move management platform API." },
  components: {
    schemas: {
      Error: { type: "object", required: ["error","code"], properties: { error: { type: "string" }, code: { type: "string" }, correlationId: { type: "string" } } },
      Meta: { type: "object", required: ["count","limit","offset"], properties: { count: { type: "integer" }, limit: { type: "integer" }, offset: { type: "integer" } } },
      Contact: { type: "object", required: ["id","customerId","firstName","lastName","email","isPrimary"], properties: { id: { type: "string", format: "uuid" }, customerId: { type: "string", format: "uuid" }, firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" }, isPrimary: { type: "boolean" } } },
      Customer: { type: "object", required: ["id","tenantId","userId","firstName","lastName","email","contacts"], properties: { id: { type: "string", format: "uuid" }, tenantId: { type: "string", format: "uuid" }, userId: { type: "string" }, firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" }, accountId: { type: "string" }, leadSourceId: { type: "string" }, contacts: { type: "array", items: ref("#/components/schemas/Contact") }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } } },
    },
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
  },
  paths: {
    "/health": { get: { operationId: "getHealth", summary: "Health check", description: "API liveness. ?deep=true probes the database.", tags: ["System"], parameters: [{ name: "deep", in: "query", required: false, schema: { type: "boolean" } }], responses: { "200": { description: "Healthy", content: { "application/json": { schema: { type: "object", required: ["status","timestamp"], properties: { status: { type: "string", enum: ["ok","degraded"] }, db: { type: "string", enum: ["ok","error"] }, timestamp: { type: "string", format: "date-time" } } } } } }, "503": { description: "DB unreachable", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } } },
    "/api/v1/customers": { get: { operationId: "listCustomers", summary: "List customers", tags: ["Customers"], security: [{ bearerAuth: [] }], parameters: [{ name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100, default: 50 } },{ name: "offset", in: "query", required: false, schema: { type: "integer", minimum: 0, default: 0 } }], responses: { "200": { description: "List", content: { "application/json": { schema: { type: "object", required: ["data","meta"], properties: { data: { type: "array", items: ref("#/components/schemas/Customer") }, meta: ref("#/components/schemas/Meta") } } } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } },
      post: { operationId: "createCustomer", summary: "Create customer", tags: ["Customers"], security: [{ bearerAuth: [] }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["userId","firstName","lastName","email","primaryContact"], properties: { userId: { type: "string" }, firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" }, accountId: { type: "string" }, leadSourceId: { type: "string" }, primaryContact: { type: "object", required: ["firstName","lastName","email"], properties: { firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" } } } } } } } }, responses: { "201": { description: "Created", content: { "application/json": { schema: { type: "object", required: ["data"], properties: { data: ref("#/components/schemas/Customer") } } } } }, "400": { description: "Validation", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } } } },
    "/api/v1/customers/{id}": { get: { operationId: "getCustomer", summary: "Get customer", tags: ["Customers"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Found", content: { "application/json": { schema: { type: "object", required: ["data"], properties: { data: ref("#/components/schemas/Customer") } } } } }, "404": { description: "Not found", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } },
      put: { operationId: "updateCustomer", summary: "Update customer", tags: ["Customers"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", properties: { firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" } } } } } }, responses: { "200": { description: "Updated", content: { "application/json": { schema: { type: "object", required: ["data"], properties: { data: ref("#/components/schemas/Customer") } } } } }, "400": { description: "Validation", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "404": { description: "Not found", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } }, delete: { operationId: "deleteCustomer", summary: "Delete customer", tags: ["Customers"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "204": { description: "Deleted" }, "404": { description: "Not found", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } } },
    "/api/v1/customers/{id}/contacts": { post: { operationId: "createContact", summary: "Add contact", tags: ["Customers"], security: [{ bearerAuth: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["firstName","lastName","email"], properties: { firstName: { type: "string" }, lastName: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" }, isPrimary: { type: "boolean" } } } } } }, responses: { "201": { description: "Created", content: { "application/json": { schema: { type: "object", required: ["data"], properties: { data: ref("#/components/schemas/Contact") } } } } }, "400": { description: "Validation", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "404": { description: "Not found", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } } },
    "/api/v1/customers/{customerId}/quotes": { get: { operationId: "listCustomerQuotes", summary: "List customer quotes", tags: ["Customers","Quotes"], security: [{ bearerAuth: [] }], parameters: [{ name: "customerId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { "200": { description: "Quotes", content: { "application/json": { schema: { type: "object", required: ["data","meta"], properties: { data: { type: "array", items: { type: "object" } }, meta: { type: "object", required: ["count"], properties: { count: { type: "integer" } } } } } } } }, "404": { description: "Not found", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "422": { description: "No primary contact", content: { "application/json": { schema: ref("#/components/schemas/Error") } } }, "500": { description: "Error", content: { "application/json": { schema: ref("#/components/schemas/Error") } } } } } },
  },
}
