// ---------------------------------------------------------------------------
// Unit tests for the workflow artifact validator (Phase 3 Unit 6)
//
// Pure functions, no I/O beyond reading committed fixture files. Fixtures
// live in src/__tests__/fixtures/workflow-artifacts/:
//
//   stdlib-send-quote-followup.zip — generated by running the REAL SDK
//     packaging code (packages/workflows-sdk-python .../cli/package.py
//     `package_project`) against packages/workflows-stdlib. This is the SDK
//     parity tripwire: if `pegasus-workflows package` changes its zip layout,
//     regenerate this fixture and revisit resolveEntryPoint.
//   not-a-zip.bin — plain text bytes
//   traversal.zip — contains a `../evil.py` entry (python zipfile ZipInfo)
//
// Awkward-to-commit shapes (>10k entries, zip64 markers, corrupt central
// directories) are built in-memory by `buildZip` below, which writes the
// minimal STORED-entry zip structure our central-directory reader consumes.
// ---------------------------------------------------------------------------

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { describe, it, expect } from 'vitest'
import {
  MAX_EXECUTABLE_ARTIFACT_BYTES,
  MAX_ZIP_ENTRIES,
  readZipEntryNames,
  resolveEntryPoint,
  sha256Hex,
  validateWorkflowArtifact,
} from './workflow-artifact'

const FIXTURES = join(__dirname, '..', '__tests__', 'fixtures', 'workflow-artifacts')
const REPO_ROOT = join(__dirname, '..', '..', '..', '..')

const stdlibZip = readFileSync(join(FIXTURES, 'stdlib-send-quote-followup.zip'))
const notAZip = readFileSync(join(FIXTURES, 'not-a-zip.bin'))
const traversalZip = readFileSync(join(FIXTURES, 'traversal.zip'))

// ---------------------------------------------------------------------------
// In-memory zip builder (STORED entries, empty contents)
// ---------------------------------------------------------------------------

type BuildZipOptions = {
  /** Override the EOCD total-entry-count field (e.g. 0xffff for zip64). */
  eocdTotalEntries?: number
  /** Append a zip64 EOCD locator record directly before the EOCD. */
  zip64Locator?: boolean
  /** Trailing zip comment. */
  comment?: string
}

function buildZip(names: string[], opts: BuildZipOptions = {}): Buffer {
  const localParts: Buffer[] = []
  const centralParts: Buffer[] = []
  let offset = 0
  for (const name of names) {
    const n = Buffer.from(name, 'utf8')
    const local = Buffer.alloc(30)
    local.writeUInt32LE(0x04034b50, 0) // local file header signature
    local.writeUInt16LE(20, 4) // version needed
    local.writeUInt16LE(n.length, 26) // file name length
    localParts.push(local, n)

    const central = Buffer.alloc(46)
    central.writeUInt32LE(0x02014b50, 0) // central directory header signature
    central.writeUInt16LE(20, 6) // version needed
    central.writeUInt16LE(n.length, 28) // file name length
    central.writeUInt32LE(offset, 42) // local header offset
    centralParts.push(central, n)
    offset += 30 + n.length
  }
  const centralDir = Buffer.concat(centralParts)
  const comment = Buffer.from(opts.comment ?? '', 'utf8')

  const locator = Buffer.alloc(opts.zip64Locator ? 20 : 0)
  if (opts.zip64Locator) locator.writeUInt32LE(0x07064b50, 0)

  const eocd = Buffer.alloc(22)
  eocd.writeUInt32LE(0x06054b50, 0) // EOCD signature
  eocd.writeUInt16LE(Math.min(names.length, 0xffff), 8) // entries on this disk
  eocd.writeUInt16LE(opts.eocdTotalEntries ?? Math.min(names.length, 0xffff), 10)
  eocd.writeUInt32LE(centralDir.length, 12)
  eocd.writeUInt32LE(offset, 16) // central directory offset
  eocd.writeUInt16LE(comment.length, 20)

  return Buffer.concat([...localParts, centralDir, locator, eocd, comment])
}

// ---------------------------------------------------------------------------
// sha256Hex
// ---------------------------------------------------------------------------

describe('sha256Hex', () => {
  it('matches node:crypto for the stdlib fixture', () => {
    const expected = createHash('sha256').update(stdlibZip).digest('hex')
    expect(sha256Hex(stdlibZip)).toBe(expected)
    expect(sha256Hex(stdlibZip)).toMatch(/^[0-9a-f]{64}$/)
  })
})

// ---------------------------------------------------------------------------
// readZipEntryNames
// ---------------------------------------------------------------------------

describe('readZipEntryNames', () => {
  it('reads the entry names of the SDK-produced stdlib artifact', () => {
    const result = readZipEntryNames(stdlibZip)
    expect(result).toEqual({
      ok: true,
      entryNames: [
        'send_quote_followup/__init__.py',
        'send_quote_followup/workflow.py',
        'pegasus-workflows.toml',
      ],
    })
  })

  it('reads an in-memory zip built by buildZip (builder sanity check)', () => {
    const result = readZipEntryNames(buildZip(['a/b.py', 'c.txt']))
    expect(result).toEqual({ ok: true, entryNames: ['a/b.py', 'c.txt'] })
  })

  it('handles a zip with a trailing comment', () => {
    const result = readZipEntryNames(buildZip(['a.py'], { comment: 'hello PK\x05\x06 world' }))
    expect(result).toEqual({ ok: true, entryNames: ['a.py'] })
  })

  it('rejects non-zip bytes', () => {
    const result = readZipEntryNames(notAZip)
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.problem).toContain('not a zip')
  })

  it('rejects an empty/too-small buffer', () => {
    expect(readZipEntryNames(Buffer.alloc(0)).ok).toBe(false)
    expect(readZipEntryNames(Buffer.alloc(10)).ok).toBe(false)
  })

  it('rejects a zip with a .. traversal entry (committed fixture)', () => {
    const result = readZipEntryNames(traversalZip)
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.problem).toContain('unsafe entry path')
  })

  it.each([
    ['../escape.py'],
    ['a/../../escape.py'],
    ['/etc/passwd'],
    ['\\\\server\\share\\x.py'],
    ['C:/windows/evil.py'],
    ['a\\..\\b.py'],
    [''],
  ])('rejects unsafe entry path %j (in-memory)', (name) => {
    const result = readZipEntryNames(buildZip(['ok.py', name]))
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.problem).toContain('unsafe entry path')
  })

  it(`rejects more than ${MAX_ZIP_ENTRIES} entries`, () => {
    const names = Array.from({ length: MAX_ZIP_ENTRIES + 1 }, (_, i) => `f${i}.py`)
    const result = readZipEntryNames(buildZip(names))
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.problem).toContain('too many entries')
  })

  it(`accepts exactly ${MAX_ZIP_ENTRIES} entries`, () => {
    const names = Array.from({ length: MAX_ZIP_ENTRIES }, (_, i) => `f${i}.py`)
    const result = readZipEntryNames(buildZip(names))
    expect(result.ok).toBe(true)
  })

  it('rejects a zip64 EOCD locator', () => {
    const result = readZipEntryNames(buildZip(['a.py'], { zip64Locator: true }))
    expect(result).toEqual({ ok: false, problem: 'zip64 archives are not supported' })
  })

  it('rejects zip64 sentinel entry counts', () => {
    const result = readZipEntryNames(buildZip(['a.py'], { eocdTotalEntries: 0xffff }))
    expect(result).toEqual({ ok: false, problem: 'zip64 archives are not supported' })
  })

  it('rejects a corrupt central directory (entry count larger than directory)', () => {
    const result = readZipEntryNames(buildZip(['a.py'], { eocdTotalEntries: 3 }))
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.problem).toContain('corrupt')
  })
})

// ---------------------------------------------------------------------------
// resolveEntryPoint
// ---------------------------------------------------------------------------

describe('resolveEntryPoint', () => {
  const entries = new Set([
    'send_quote_followup/__init__.py',
    'send_quote_followup/workflow.py',
    'pegasus-workflows.toml',
  ])

  it('resolves a module file (the real stdlib entry point)', () => {
    expect(resolveEntryPoint('send_quote_followup.workflow:SendQuoteFollowup', entries)).toBe(
      'send_quote_followup/workflow.py',
    )
  })

  it('resolves a package __init__', () => {
    expect(resolveEntryPoint('send_quote_followup:Something', entries)).toBe(
      'send_quote_followup/__init__.py',
    )
  })

  it('returns null for a missing module', () => {
    expect(resolveEntryPoint('send_quote_followup.missing:X', entries)).toBeNull()
  })

  it.each([
    ['no_colon'],
    [':NoModule'],
    ['module.path:'],
    ['has space.module:X'],
    ['a..b:X'],
    ['a/b:X'],
    ['../a:X'],
  ])('returns null for malformed entry point %j', (ep) => {
    expect(resolveEntryPoint(ep, entries)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// validateWorkflowArtifact
// ---------------------------------------------------------------------------

describe('validateWorkflowArtifact', () => {
  it('accepts the REAL stdlib artifact + entry point (SDK parity tripwire)', () => {
    const result = validateWorkflowArtifact(stdlibZip, {
      entryPoints: ['send_quote_followup.workflow:SendQuoteFollowup'],
    })
    expect(result).toEqual({
      ok: true,
      sha256: createHash('sha256').update(stdlibZip).digest('hex'),
      sizeBytes: stdlibZip.length,
    })
  })

  it('pins the stdlib manifest the fixture was generated from (regenerate on drift)', () => {
    // If this fails, packages/workflows-stdlib changed its layout or entry
    // points: regenerate stdlib-send-quote-followup.zip with the SDK
    // packaging code and update the assertions in this file (see the header
    // comment for the recipe).
    const toml = readFileSync(
      join(REPO_ROOT, 'packages', 'workflows-stdlib', 'pegasus-workflows.toml'),
      'utf8',
    )
    expect(toml).toContain('entry_points = ["send_quote_followup.workflow:SendQuoteFollowup"]')
    expect(toml).toContain('source_dir = "send_quote_followup"')
  })

  it('rejects non-zip bytes with a single structural problem', () => {
    const result = validateWorkflowArtifact(notAZip, { entryPoints: ['a:B'] })
    expect(result.ok).toBe(false)
    if (!result.ok) {
      expect(result.problems).toHaveLength(1)
      expect(result.problems[0]).toContain('not a zip')
    }
  })

  it('rejects an artifact whose entry point does not resolve, naming the candidates', () => {
    const result = validateWorkflowArtifact(stdlibZip, {
      entryPoints: ['workflows.send_quote_followup:SendQuoteFollowup'],
    })
    expect(result.ok).toBe(false)
    if (!result.ok) {
      expect(result.problems).toHaveLength(1)
      expect(result.problems[0]).toContain('workflows.send_quote_followup:SendQuoteFollowup')
      expect(result.problems[0]).toContain('workflows/send_quote_followup.py')
    }
  })

  it('collects one problem per unresolved entry point', () => {
    const result = validateWorkflowArtifact(stdlibZip, {
      entryPoints: [
        'send_quote_followup.workflow:SendQuoteFollowup', // resolves
        'missing.module:A', // does not
        'also.missing:B', // does not
      ],
    })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.problems).toHaveLength(2)
  })

  it('rejects dependency manifests anywhere in the tree', () => {
    const zip = buildZip(['pkg/__init__.py', 'pkg/requirements.txt', 'PYPROJECT.TOML'])
    const result = validateWorkflowArtifact(zip, { entryPoints: ['pkg:X'] })
    expect(result.ok).toBe(false)
    if (!result.ok) {
      expect(result.problems).toHaveLength(2)
      expect(result.problems.join('\n')).toContain('pkg/requirements.txt')
      expect(result.problems.join('\n')).toContain('pip dependencies are not allowed')
    }
  })

  it('does not flag pegasus-workflows.toml as a dependency manifest', () => {
    const result = validateWorkflowArtifact(stdlibZip, {
      entryPoints: ['send_quote_followup.workflow:SendQuoteFollowup'],
    })
    expect(result.ok).toBe(true)
  })

  it('exports a 10 MB cap for the finalize pre-check', () => {
    expect(MAX_EXECUTABLE_ARTIFACT_BYTES).toBe(10 * 1024 * 1024)
  })
})
