import { empty, eqNum, eq, static_, like } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const budgetEntities: EntityConfig[] = [
  {
    slug: 'budgets',
    tableName: 'budget',
    idField: 'budget_num',
    codeField: 'budget_num',
    idType: 'integer',
    orderBy: 'ORDER BY budget_num DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'budget_num'),
      eqNum('CODE', 'budget_num'),
      eqNum('BUDGETNUM', 'budget_num'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('ORDERNUMBER', 'order_num'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'budget-masters',
    tableName: 'budgetmaster',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('BUDGETNUM', 'budget_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
  {
    slug: 'budget-details',
    tableName: 'budgetdetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('BUDGETNUM', 'budget_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
  {
    slug: 'budget-qmm',
    tableName: 'budget',
    idField: 'budget_num',
    codeField: 'budget_num',
    idType: 'integer',
    orderBy: 'ORDER BY budget_num DESC',
    searchKeywords: [empty(), eqNum('ID', 'budget_num'), eqNum('ORDERNUM', 'order_num')],
  },
  {
    slug: 'quotes',
    tableName: 'quotes',
    idField: 'quote_number',
    codeField: 'quote_number',
    idType: 'integer',
    orderBy: 'ORDER BY quote_number DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'quote_number'),
      eqNum('CODE', 'quote_number'),
      eqNum('QUOTENUM', 'quote_number'),
      eqNum('QUOTENUMBER', 'quote_number'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('ORDERNUMBER', 'order_num'),
      eq('BRANCH', 'branch'),
      like('SHIPPER', 'shipper_name'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
    freeTextColumns: ['shipper_name'],
  },
  {
    slug: 'quote-memos',
    tableName: 'memos',
    idField: 'memo_id',
    codeField: 'memo_id',
    idType: 'integer',
    orderBy: 'ORDER BY memo_id DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'memo_id'),
      eqNum('QUOTENUM', 'quote_number'),
      eqNum('QUOTENUMBER', 'quote_number'),
      eqNum('PERSON', 'person'),
    ],
  },
]
