import { empty, eqNum, eq, like, static_ } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const employeeEntities: EntityConfig[] = [
  {
    slug: 'employees',
    tableName: 'salesman',
    idField: 'id',
    codeField: 'code',
    idType: 'integer',
    orderBy: 'ORDER BY name',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'code'),
      like('NAME', 'name'),
      eq('BRANCH', 'branch'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
    freeTextColumns: ['name', 'code'],
  },
  {
    slug: 'employee-timesheets',
    tableName: 'employeetimesheets',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('EMPLOYEEID', 'employee_id'),
      eqNum('EMPLOYEE', 'employee_id'),
    ],
  },
  {
    slug: 'employee-benefit-hours-master',
    tableName: 'EmpBenefitHrsMaster',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('EMPLOYEEID', 'employee_id')],
  },
  {
    slug: 'employee-benefit-hours-detail',
    tableName: 'EmpBenefitHrsDetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('MASTERID', 'master_id')],
  },
  {
    slug: 'salesman-commission-masters',
    tableName: 'invoicemaster',
    idField: 'invoice_num',
    codeField: 'invoice_num',
    idType: 'integer',
    orderBy: 'ORDER BY invoice_num DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'invoice_num'),
      eqNum('INVOICENUM', 'invoice_num'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('SM', 'sm'),
    ],
  },
  {
    slug: 'salesman-commission-details',
    tableName: 'commdetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('INVOICENUM', 'invoice_num'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
  {
    slug: 'salesman-commission-rate-lines',
    tableName: 'sm_commrates',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('SM', 'sm_id')],
  },
  {
    slug: 'salesman-budgets',
    tableName: 'smbudget',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('SM', 'sm_id')],
  },
  {
    slug: 'salesman-debits',
    tableName: 'sm_debits',
    idField: 'entry_no',
    codeField: 'entry_no',
    idType: 'integer',
    orderBy: 'ORDER BY entry_no DESC',
    searchKeywords: [
      empty(),
      eqNum('ID', 'entry_no'),
      eqNum('SM', 'sm_id'),
      eqNum('ORDERNUM', 'order_num'),
    ],
  },
  {
    slug: 'salesman-commission-nw-masters',
    tableName: 'SalesmanCommissionNWMaster',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id DESC',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('SM', 'sm_id')],
  },
  {
    slug: 'salesman-commission-nw-details',
    tableName: 'SalesmanCommissionNWDetail',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('MASTERID', 'master_id')],
  },
  {
    slug: 'salesman-commission-nw-tariffs',
    tableName: 'SalesmanCommissionNWTariffs',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'salesman-commission-nw-schedules',
    tableName: 'SalesmanCommissionNWSchedules',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id')],
  },
  {
    slug: 'master-salesman-ytd-summary-fields',
    tableName: 'MasterSalesmanYTDSummaryCodes',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [eqNum('ID', 'id')],
  },
  {
    slug: 'atlas-salesman-items',
    tableName: 'atlassalesmanitems',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('SM', 'sm_id')],
  },
]
