import { empty, eqNum, eq, like, static_ } from '../keyword-helpers'
import type { EntityConfig } from '../types'

export const saleEntities: EntityConfig[] = [
  {
    slug: 'sales',
    tableName: 'sales',
    idField: 'order_num',
    codeField: 'order_num',
    idType: 'integer',
    orderBy: 'ORDER BY order_num',
    searchKeywords: [
      empty(),
      eqNum('ID', 'order_num'),
      eqNum('CODE', 'order_num'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('ORDERNUMBER', 'order_num'),
      eq('AVL', 'avl_reg'),
      eq('AVLREG', 'avl_reg'),
      eq('REGISTRATION', 'avl_reg'),
      eq('GLOBALCOM', 'globalcom_ref'),
      eq('GCREF', 'globalcom_ref'),
      eq('BRANCH', 'branch'),
      eqNum('COORDINATOR', 'coordinator_id'),
      eqNum('COORDINATORID', 'coordinator_id'),
      eqNum('SALESMAN', 'sm'),
      eqNum('SM', 'sm'),
      eqNum('FC', 'fc_id'),
      eqNum('FCID', 'fc_id'),
      eqNum('OPERATIONS', 'operations_id'),
      like('SHIPPER', 'shipper_name'),
      like('SHIPPERNAME', 'shipper_name'),
      like('SHIPPERCITY', 'shipper_city'),
      eq('SHIPPERSTATE', 'shipper_state'),
      like('CONSIGNEECITY', 'consignee_city'),
      eq('CONSIGNEESTATE', 'consignee_state'),
      eq('BOOKINGAGENT', 'ba_name'),
      eq('BA', 'ba_name'),
      eq('HAULMODE', 'haul_mode'),
      eq('ACCOUNT', 'national_acct_code'),
      eq('NATIONALACCOUNT', 'national_acct_code'),
      static_('VIP', "vip='Y'"),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
    freeTextColumns: ['shipper_name', 'consignee_city', 'ba_name'],
  },
  {
    slug: 'sale-documents',
    tableName: 'sale_documents',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY id',
    listFields: "active, order_num, date_completed, type_id, type_desc, '' AS code, id",
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('ORDERNUMBER', 'order_num'),
      eqNum('TYPE', 'type_id'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'sale-invoices',
    tableName: 'invoice',
    idField: 'id',
    codeField: 'rvs_num',
    idType: 'integer',
    orderBy: 'ORDER BY rvs_num',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eq('CODE', 'rvs_num'),
      eq('RVSNUM', 'rvs_num'),
      eqNum('ORDERNUM', 'order_num'),
      static_('ACTIVE', "active='Y'"),
    ],
  },
  {
    slug: 'sale-international',
    tableName: 'salesinternational',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY order_num, id',
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('ORDERNUM', 'order_num')],
  },
  {
    slug: 'sale-storage',
    tableName: 'salesstorageinfo',
    idField: 'id',
    codeField: 'order_num',
    idType: 'integer',
    orderBy: 'ORDER BY order_num, id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('ORDERNUM', 'order_num'),
      eqNum('CODE', 'order_num'),
    ],
  },
  {
    slug: 'sale-atlas',
    tableName: 'salesatlas',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY order_num, id',
    listFields: "order_num, booking_division, '' AS code, id",
    searchKeywords: [empty(), eqNum('ID', 'id'), eqNum('ORDERNUM', 'order_num')],
  },
  {
    slug: 'sale-service-auths',
    tableName: 'salesserviceauths',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY [sequence], [id]',
    listFields:
      "active, order_number, account_code, is_requested_origin, is_requested_destin, auth_status, description, auth_date, auth_acct_contact, LTRIM(RTRIM(CONCAT(notes,'   ',account_notes))) AS notes, user_can_edit_desc, sequence, master_id, '9999999' AS code, id",
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('ORDERNUM', 'order_number'),
      eqNum('ORDERNUMBER', 'order_number'),
      eq('ACCOUNT', 'account_code'),
      eq('ACCOUNTCODE', 'account_code'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'qos-audit-master',
    tableName: 'qsaanswersmaster',
    idField: 'id',
    codeField: 'id',
    idType: 'integer',
    orderBy: 'ORDER BY order_number, id',
    listFields:
      'active, order_number, id AS qsa_num, shipment_type, coordinator_id, salesman_id, shipper_name, national_acct_code, rating, rating_description, date_created, id AS code, id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('ORDERNUM', 'order_number'),
      eqNum('ORDERNUMBER', 'order_number'),
      static_('ACTIVE', "active='Y'"),
      static_('NOTACTIVE', "active='N'"),
    ],
  },
  {
    slug: 'qos-audit-detail',
    tableName: 'qsaanswersdetail',
    idField: 'id',
    codeField: 'master_id',
    idType: 'integer',
    orderBy: 'ORDER BY order_number, master_id, id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'id'),
      eqNum('MASTERID', 'master_id'),
      eqNum('ORDERNUM', 'order_number'),
      eqNum('ORDERNUMBER', 'order_number'),
    ],
  },
  {
    slug: 'memos',
    tableName: 'memos',
    idField: 'memo_id',
    codeField: 'memo_id',
    idType: 'integer',
    orderBy: 'ORDER BY memo_id DESC',
    listFields:
      'memo_status, quote_number, order_memo, memo_shipper, call_date, next_date, next_action, memo_type, action, who_called, regarding, person, call_time, branch_id, memo_id AS id',
    searchKeywords: [
      empty(),
      eqNum('ID', 'memo_id'),
      eqNum('ORDERNUM', 'order_memo'),
      eqNum('ORDERNUMBER', 'order_memo'),
      eqNum('QUOTENUM', 'quote_number'),
      eqNum('QUOTENUMBER', 'quote_number'),
      eqNum('PERSON', 'person'),
      eq('BRANCH', 'branch_id'),
      {
        keyword: 'NEEDACK',
        toSql: () => {
          const today = new Date()
          const mm = String(today.getMonth() + 1).padStart(2, '0')
          const dd = String(today.getDate()).padStart(2, '0')
          const yyyy = today.getFullYear()
          return `(memo_status='N')AND(next_date <= '${mm}/${dd}/${yyyy}')`
        },
      },
      static_('ACTIVE', "memo_status='Y'"),
    ],
    freeTextColumns: ['who_called', 'regarding'],
  },
]
